// Findings — Bible §3 + §T.2.6
// Severity-sorted table, slide-in detail panel, sync from run
"use client";

import useSWR from "swr";
import { useParams } from "next/navigation";
import { useAuth } from "@/contexts/AuthContext";
import { listFindings, syncFindings, getAudit } from "@/lib/api";
import { PageHeader } from "@/components/ui/PageHeader";
import { Badge } from "@/components/ui/Badge";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { DetailPanel } from "@/components/ui/DetailPanel";
import { PageSkeleton } from "@/components/ui/LoadingSkeleton";
import { ErrorMessage } from "@/components/ui/ErrorMessage";
import { useToast } from "@/components/ui/Toast";
import { cn } from "@/lib/utils";
import { useState, useCallback } from "react";
import type { FindingRow } from "@/lib/types";
import { RefreshCw, AlertTriangle, Flame, Info } from "lucide-react";

const SEVERITY_ORDER: Record<string, number> = {
  CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3,
};

const SEVERITY_LEFT_BORDER: Record<string, string> = {
  CRITICAL: "border-l-[3px] border-l-danger-base",
  HIGH:     "border-l-[2px] border-l-warning-base",
  MEDIUM:   "border-l-[2px] border-l-amber-400",
  LOW:      "border-l border-l-neutral-200",
};

const SEVERITY_ICON: Record<string, React.ComponentType<{ className?: string }>> = {
  CRITICAL: Flame,
  HIGH:     AlertTriangle,
  MEDIUM:   Info,
  LOW:      Info,
};

function SeverityIcon({ severity }: { severity: string }) {
  const s = severity.toUpperCase();
  const Icon = SEVERITY_ICON[s] ?? Info;
  const cls =
    s === "CRITICAL" ? "text-danger-base" :
    s === "HIGH"     ? "text-warning-base" :
    s === "MEDIUM"   ? "text-warning-base" :
                       "text-neutral-400";
  return <Icon className={cn("h-4 w-4", cls)} />;
}

function FindingDetail({ finding }: { finding: FindingRow }) {
  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center gap-2 flex-wrap">
        <Badge variant={finding.severity.toLowerCase()} />
        <Badge variant={finding.finding_type.toLowerCase()} />
      </div>
      <div>
        <p className="text-11 font-medium text-neutral-500 uppercase tracking-wider mb-1">Finding ID</p>
        <p className="text-13 font-mono text-neutral-600">{finding.finding_id}</p>
      </div>
      <div>
        <p className="text-11 font-medium text-neutral-500 uppercase tracking-wider mb-1">Title</p>
        <p className="text-14 text-neutral-800 font-medium">{finding.title}</p>
      </div>
      {finding.detail && (
        <div>
          <p className="text-11 font-medium text-neutral-500 uppercase tracking-wider mb-1">Gap / Detail</p>
          <p className="text-14 text-neutral-700 leading-relaxed">{finding.detail}</p>
        </div>
      )}
      <div>
        <p className="text-11 font-medium text-neutral-500 uppercase tracking-wider mb-1">Type</p>
        <p className="text-13 font-mono text-neutral-600">{finding.finding_type}</p>
      </div>
      <div className="mt-8 pt-4 border-t border-neutral-100">
        <p className="text-12 text-neutral-400">
          Findings are deterministic — generated by the audit engine, not a model.
          The verdict cannot be changed without re-running the audit.
        </p>
      </div>
    </div>
  );
}

export default function FindingsPage() {
  const { auditId } = useParams<{ auditId: string }>();
  const { userId } = useAuth();
  const { toast } = useToast();
  const [syncing, setSyncing] = useState(false);
  const [selectedFinding, setSelectedFinding] = useState<FindingRow | null>(null);
  const [panelOpen, setPanelOpen] = useState(false);

  const { data: audit } = useSWR(
    userId && auditId ? ["audit", auditId, userId] : null,
    ([, id, uid]) => getAudit(uid, id),
  );

  const { data: findings, error, isLoading, mutate } = useSWR(
    userId && auditId ? ["findings", auditId, userId] : null,
    ([, id, uid]) => listFindings(uid, id),
    { refreshInterval: 15_000 },
  );

  const handleRowClick = useCallback((row: FindingRow) => {
    setSelectedFinding(row);
    setPanelOpen(true);
  }, []);

  const closePanel = useCallback(() => setPanelOpen(false), []);

  async function handleSync() {
    setSyncing(true);
    try {
      await syncFindings(userId!, auditId);
      await mutate();
      toast({ type: "success", title: "Findings synced from latest run" });
    } catch (err: unknown) {
      toast({
        type: "error",
        title: "Sync failed",
        description: err instanceof Error ? err.message : "Unknown error",
      });
    } finally {
      setSyncing(false);
    }
  }

  if (isLoading) return <PageSkeleton />;
  if (error) return <ErrorMessage message={error.message} onRetry={() => mutate()} />;

  const rows = [...(findings?.rows ?? [])].sort(
    (a, b) =>
      (SEVERITY_ORDER[a.severity.toUpperCase()] ?? 9) -
      (SEVERITY_ORDER[b.severity.toUpperCase()] ?? 9),
  );

  const criticalCount = rows.filter((r) => r.severity.toUpperCase() === "CRITICAL").length;
  const highCount     = rows.filter((r) => r.severity.toUpperCase() === "HIGH").length;
  const totalFindings = findings?.total_findings ?? 0;

  return (
    <>
      <PageHeader
        title="Findings"
        subtitle={audit?.system_name}
        breadcrumbs={[
          { label: "Audits", href: "/audits" },
          { label: audit?.system_name ?? auditId, href: `/audits/${auditId}` },
          { label: "Findings" },
        ]}
        action={
          <Button variant="secondary" size="sm" loading={syncing} iconLeft={<RefreshCw />} onClick={handleSync}>
            Sync from Run
          </Button>
        }
      />

      {/* Stats strip */}
      <div className="flex items-center gap-6 mb-6 px-1">
        {[
          { label: "Total findings", value: totalFindings, variant: totalFindings > 0 ? "danger" : "" },
          { label: "Critical", value: criticalCount, variant: criticalCount > 0 ? "danger" : "" },
          { label: "High", value: highCount, variant: highCount > 0 ? "warning" : "" },
        ].map(({ label, value, variant }) => (
          <div key={label}>
            <p className={cn(
              "text-22 font-medium",
              variant === "danger" ? "text-danger-base" :
              variant === "warning" ? "text-warning-base" :
              "text-neutral-800",
            )}>{value}</p>
            <p className="text-13 text-neutral-500">{label}</p>
          </div>
        ))}
      </div>

      {rows.length === 0 ? (
        <Card className="text-center py-16">
          <AlertTriangle className="h-8 w-8 text-neutral-300 mx-auto mb-4" />
          <p className="text-16 font-medium text-neutral-700">No findings</p>
          <p className="text-14 text-neutral-400 mt-2">Run the audit and sync findings to see results.</p>
          <div className="mt-6">
            <Button variant="secondary" size="sm" loading={syncing} onClick={handleSync}>
              Sync from Run
            </Button>
          </div>
        </Card>
      ) : (
        <div className="rounded-md border border-neutral-200 overflow-hidden">
          <table className="w-full">
            <thead>
              <tr className="bg-neutral-50 border-b border-neutral-200">
                {["", "Severity", "Type", "Title", "Finding ID"].map((h, i) => (
                  <th key={i} className={cn(
                    "px-4 py-3 text-left text-11 font-medium text-neutral-500 uppercase tracking-wider",
                    i === 0 && "w-1 px-0",
                    i === 1 && "w-28",
                    i === 4 && "w-48",
                  )}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-100 bg-white">
              {rows.map((row) => {
                const isSelected = panelOpen && selectedFinding?.finding_id === row.finding_id;
                const borderCls = SEVERITY_LEFT_BORDER[row.severity.toUpperCase()] ?? "border-l border-l-neutral-200";
                return (
                  <tr
                    key={row.finding_id}
                    onClick={() => handleRowClick(row)}
                    className={cn(
                      "h-[52px] cursor-pointer transition-colors duration-base",
                      borderCls,
                      isSelected ? "bg-brand-50" : "hover:bg-neutral-50",
                    )}
                  >
                    <td className="w-0 px-0" />
                    <td className="px-4 py-0 w-28">
                      <div className="flex items-center gap-1.5">
                        <SeverityIcon severity={row.severity} />
                        <Badge variant={row.severity.toLowerCase()} />
                      </div>
                    </td>
                    <td className="px-4 py-0 w-40">
                      <span className="text-12 font-mono text-neutral-500">{row.finding_type}</span>
                    </td>
                    <td className="px-4 py-0">
                      <div className="text-14 font-medium text-neutral-800">{row.title}</div>
                      {row.detail && (
                        <div className="text-12 text-neutral-400 mt-0.5 truncate max-w-md">{row.detail}</div>
                      )}
                    </td>
                    <td className="px-4 py-0 w-48">
                      <span className="text-12 font-mono text-neutral-400">{row.finding_id}</span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      <DetailPanel
        isOpen={panelOpen}
        onClose={closePanel}
        title={selectedFinding?.title ?? "Finding Detail"}
        subtitle={selectedFinding?.finding_id}
        width={480}
      >
        {selectedFinding && <FindingDetail finding={selectedFinding} />}
      </DetailPanel>
    </>
  );
}
