"""
Singapore Jurisdiction Pack v1 — 18 comprehensive compliance controls.
Bible §11.8 — Singapore jurisdiction-specific compliance framework.

Domains:
- AML/KYC (7 controls): SG-AML-01 through SG-AML-07
- SANCTIONS (2 controls): SG-SANCTIONS-01, SG-SANCTIONS-02
- FRAUD (2 controls): SG-FRAUD-01, SG-FRAUD-02
- GOVERNANCE (2 controls): SG-GOV-01, SG-GOV-02
- LICENSING (2 controls): SG-LIC-01, SG-LIC-02
- PRIVACY (2 controls): SG-PRIVACY-01, SG-PRIVACY-02
- REAL ESTATE (1 control): SG-RE-01

Regulators: MAS (Monetary Authority of Singapore), PDPC (Personal Data Protection Commission)
Effective: 2026-01-01
"""

from app.agents.jurisdiction_types import (
    JurisdictionControl,
    JurisdictionPackMetadata,
    JurisdictionPack,
    Domain,
    JurisdictionCode,
    Regulator,
    Severity,
    EvidenceRequirement,
    RemediationTemplate,
    RealEstateOverlay,
)


SG_PACK_V1 = JurisdictionPack(
    metadata=JurisdictionPackMetadata(
        pack_id="SG-v1",
        jurisdiction=JurisdictionCode.SG,
        country_codes=["SG"],
        regulators=[
            Regulator.MAS,
            Regulator.PDPC,
        ],
        domains=[
            Domain.AML_KYC,
            Domain.SANCTIONS,
            Domain.FRAUD_TXN_MONITORING,
            Domain.GOVERNANCE_VENDOR,
            Domain.LICENSING_FILINGS,
            Domain.PRIVACY_DATA,
            Domain.REAL_ESTATE,
        ],
        version="1.0",
        source_references=[
            "https://www.mas.gov.sg/regulation/anti-money-laundering",
            "https://www.pdpc.gov.sg/",
            "https://sso.agc.gov.sg/Act/PDPA2012",
        ],
        effective_date="2026-01-01",
        priority=4,
        applicability_notes="Mandatory for all Singapore-based financial institutions and payment service providers. Non-resident entities operating in Singapore subject to same requirements. MAS Notice 626 (AML/CFT) applies.",
    ),
    controls=[
        # ═════════════════════════════════════════════════════════════════════════
        # AML/KYC DOMAIN (7 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="SG-AML-01",
            control_name="AML/CFT Program - MAS Notice 626 Framework",
            control_description="Financial institution must establish comprehensive AML/CFT program per MAS Notice 626. Program must include customer due diligence (CDD), enhanced due diligence (EDD), transaction monitoring, suspicious activity reporting (SAR), beneficial ownership identification, and audit. Program must be approved by board and documented.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 (AML/CFT Policy); Prevention of Money Laundering and Countering the Financing of Terrorism (PMLT) Act",
            severity=Severity.CRITICAL,
            regulatory_reference="MAS Notice 626 (AML/CFT Policy); PMLT Act 2002 Section 36; MAS RMCD 3.1",
            risk_if_missing="Regulatory enforcement, financial penalties up to SGD 500K+ for institutions, criminal liability, license revocation.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="AML_POLICY",
                    description="Board-approved written AML/CFT policy per MAS Notice 626 with governance structure and management responsibilities",
                    scoring_keywords=[
                        "AML program",
                        "CFT program",
                        "MAS Notice 626",
                        "board approval",
                        "AML policy",
                        "PMLT Act",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="CDD_PROCEDURE",
                    description="Customer due diligence procedures per MAS Notice 626 Section 8 including identification, beneficial ownership, and source of funds verification",
                    scoring_keywords=[
                        "CDD procedure",
                        "customer identification",
                        "MAS Notice 626",
                        "beneficial owner",
                        "source of funds",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="TRANSACTION_MONITORING",
                    description="Transaction monitoring system specifications per MAS Notice 626 Section 35 with alert rules and investigation procedures",
                    scoring_keywords=[
                        "transaction monitoring",
                        "MAS Notice 626",
                        "monitoring system",
                        "alert rules",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SAR_PROCEDURE",
                    description="Suspicious Activity Report (SAR) procedure per MAS Notice 626 Section 36 with filing requirements and escalation process",
                    scoring_keywords=[
                        "SAR procedure",
                        "suspicious activity report",
                        "MAS filing",
                        "reporting requirements",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop comprehensive AML/CFT program per MAS Notice 626. Establish board-level governance and compliance officer role. Document CDD procedures for all customer types. Implement transaction monitoring system. Create SAR filing procedures. Conduct staff training. Document audit procedures.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=60,
                    expected_evidence_after=["AML_POLICY", "PROCEDURES", "SYSTEM_CONFIG", "TRAINING_RECORDS"],
                ),
            ],
            missing_criteria=[
                "No AML/CFT program documented per MAS Notice 626",
                "No board-level governance",
                "CDD procedures not formalized",
                "No transaction monitoring system",
            ],
            partial_criteria=[
                "Program exists but not MAS Notice 626 aligned",
                "CDD procedures incomplete for certain customer types",
                "Transaction monitoring system with gaps",
            ],
            supported_criteria=[
                "Comprehensive AML/CFT program per MAS Notice 626",
                "Board-approved governance structure",
                "CDD procedures aligned with MAS requirements",
                "Automated transaction monitoring",
                "SAR filing procedure documented",
            ],
            risk_raise_criteria=[
                "Policy review overdue (>12 months)",
                "CDD not updated for high-risk customers annually",
                "Transaction monitoring system failures",
            ],
            retrieval_tags=["aml", "cft", "mas_notice_626", "aml_program"],
            corpus_hints=["AML program", "MAS Notice 626", "CFT", "PMLT Act"],
            source_types=["POLICY_DOCUMENT", "PROCEDURE_DOCUMENT", "SYSTEM_CONFIG"],
        ),
        JurisdictionControl(
            control_id="SG-AML-02",
            control_name="Customer Due Diligence (CDD) - Identity Verification and Beneficial Ownership",
            control_description="Financial institution must conduct CDD per MAS Notice 626 Section 8 for all customers before establishing relationship. CDD must include identity verification through official documents, beneficial owner identification, and assessment of business relationship purpose. CDD must be completed before account activation.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 8; PMLT Act Section 36",
            severity=Severity.CRITICAL,
            regulatory_reference="MAS Notice 626 Section 8; PMLT Act 2002 Section 36; MAS RMCD 3.1 paragraphs 3.2-3.8",
            risk_if_missing="Regulatory enforcement, inability to identify beneficial owners, failure to detect suspicious customers, financial penalties.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="CDD_SAMPLES",
                    description="Sample CDD files for minimum 5 customers showing identification documents, beneficial owner verification, and approval workflow per MAS Notice 626 Section 8",
                    scoring_keywords=[
                        "CDD file",
                        "customer identification",
                        "beneficial owner",
                        "MAS Notice 626 Section 8",
                        "ID verification",
                    ],
                    confidence_threshold=0.90,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="IDENTITY_VERIFICATION",
                    description="Documentation of identity verification against official documents (passport, national ID) with verification date and source",
                    scoring_keywords=[
                        "identity verification",
                        "official ID",
                        "passport",
                        "NRIC",
                        "verification record",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement CDD procedures per MAS Notice 626 Section 8. Establish document collection process (official ID, utility bills). Create beneficial owner identification worksheet. Develop CDD file template with mandatory fields. Implement system controls blocking account activation without complete CDD. Train staff on CDD requirements.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=40,
                    expected_evidence_after=["CDD_PROCEDURE", "CDD_FILES"],
                ),
            ],
            missing_criteria=[
                "No CDD process documented",
                "Customers onboarded without ID verification",
                "No beneficial owner identification",
            ],
            partial_criteria=[
                "CDD exists for new customers but not legacy customers",
                "Identity verified but beneficial owner not identified",
            ],
            supported_criteria=[
                "CDD completed before account activation per MAS Notice 626",
                "Identity verified against official government ID",
                "Beneficial owner identified and documented",
                "CDD file maintained with all documentation",
            ],
            risk_raise_criteria=[
                "CDD file missing for active customer",
                "Identity documents not independently verified",
                "Beneficial owner identity not documented",
            ],
            retrieval_tags=["cdd", "kyc", "aml", "identity_verification"],
            corpus_hints=["CDD procedure", "Customer identification", "MAS Notice 626", "Beneficial owner"],
            source_types=["CDD_FILE", "PROCEDURE_DOCUMENT"],
        ),
        JurisdictionControl(
            control_id="SG-AML-03",
            control_name="Enhanced Due Diligence (EDD) - High-Risk Customers and PEP Screening",
            control_description="Financial institution must apply enhanced due diligence per MAS Notice 626 Section 9 for higher-risk customers including politically exposed persons (PEPs), customers from high-risk jurisdictions (FATF list), and customers with complex ownership structures. EDD must include source of wealth verification and senior management approval.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 9; PMLT Act Section 36",
            severity=Severity.CRITICAL,
            regulatory_reference="MAS Notice 626 Section 9; PMLT Act Section 36; MAS RMCD 3.1 paragraphs 3.9-3.15",
            risk_if_missing="Facilitation of sanctions violations, money laundering through high-risk customers, regulatory enforcement.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="EDD_PROCEDURE",
                    description="Documented EDD procedure per MAS Notice 626 Section 9 defining high-risk customer categories and enhanced measures",
                    scoring_keywords=[
                        "EDD procedure",
                        "enhanced due diligence",
                        "MAS Notice 626 Section 9",
                        "high-risk customer",
                        "PEP screening",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="PEP_SCREENING",
                    description="Automated PEP screening system with integration to local and international PEP lists with monthly updates minimum",
                    scoring_keywords=[
                        "PEP screening",
                        "politically exposed person",
                        "automated screening",
                        "PEP list",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="EDD_SAMPLES",
                    description="Sample EDD files for high-risk customers showing source of funds/wealth verification and senior management approval",
                    scoring_keywords=[
                        "EDD file",
                        "source of funds",
                        "management approval",
                        "high-risk customer",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop EDD procedure per MAS Notice 626 Section 9 with risk classification system. Implement automated PEP screening with local/international lists (monthly minimum). Create source of funds verification documentation process. Establish senior management approval workflow for PEPs.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=35,
                    expected_evidence_after=["EDD_PROCEDURE", "SCREENING_SYSTEM", "EDD_FILES"],
                ),
            ],
            missing_criteria=[
                "No EDD procedure per MAS Notice 626 Section 9",
                "No PEP screening system",
                "High-risk customers not identified",
            ],
            partial_criteria=[
                "EDD process exists but not systematic",
                "Manual PEP screening without automation",
                "Management approval not consistently documented",
            ],
            supported_criteria=[
                "Comprehensive EDD procedure per MAS Notice 626 Section 9",
                "Automated PEP screening with monthly updates",
                "Source of funds verified for all high-risk customers",
                "Senior management approval documented",
            ],
            risk_raise_criteria=[
                "Identified PEP without EDD documentation",
                "PEP screening not updated in past 30 days",
            ],
            retrieval_tags=["edd", "pep", "aml", "high_risk"],
            corpus_hints=["EDD procedure", "PEP screening", "MAS Notice 626", "Enhanced due diligence"],
            source_types=["PROCEDURE_DOCUMENT", "SCREENING_SYSTEM", "EDD_FILE"],
        ),
        JurisdictionControl(
            control_id="SG-AML-04",
            control_name="Ongoing Transaction Monitoring and Suspicious Activity Detection",
            control_description="Financial institution must maintain ongoing transaction monitoring per MAS Notice 626 Section 35 to identify suspicious activities. System must generate alerts for transactions matching defined risk criteria. Alerts must be investigated and documented. Suspicious activities must be reported to MAS within 15 days.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 35; PMLT Act Section 39",
            severity=Severity.CRITICAL,
            regulatory_reference="MAS Notice 626 Section 35; PMLT Act Section 39; MAS RMCD 3.1 paragraph 3.16",
            risk_if_missing="Failure to detect money laundering and terrorist financing, regulatory enforcement, financial penalties.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="MONITORING_SYSTEM",
                    description="Transaction monitoring system documentation per MAS Notice 626 Section 35 with rules, thresholds, and procedures",
                    scoring_keywords=[
                        "transaction monitoring",
                        "MAS Notice 626 Section 35",
                        "monitoring system",
                        "alert rules",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="ALERT_SAMPLES",
                    description="Sample alerts with investigation outcomes and documentation of closure",
                    scoring_keywords=[
                        "alert",
                        "investigation",
                        "suspicious activity",
                        "case closure",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="MONITORING_PROCEDURE",
                    description="Alert investigation and escalation procedure with timelines",
                    scoring_keywords=[
                        "monitoring procedure",
                        "alert investigation",
                        "escalation process",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement automated transaction monitoring system per MAS Notice 626 Section 35 with rules for high-value transactions (>SGD 100K), round-tripping, rapid transfers, unusual patterns. Establish alert investigation procedure with 5-day response time. Create SAR escalation path. Train investigators.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=45,
                    expected_evidence_after=["SYSTEM_CONFIG", "ALERT_SAMPLES", "PROCEDURE"],
                ),
            ],
            missing_criteria=[
                "No transaction monitoring system",
                "Monitoring rules not documented",
                "No alert investigation procedure",
            ],
            partial_criteria=[
                "Manual monitoring without systematic rules",
                "Alert investigation inconsistent or delayed",
            ],
            supported_criteria=[
                "Automated monitoring system per MAS Notice 626 Section 35",
                "Alerts generated for suspicious patterns",
                "Timely investigation (5 business days)",
                "Clear SAR escalation path documented",
            ],
            risk_raise_criteria=[
                "High-value transactions not monitored",
                "Alert backlog exceeding 30 days",
                "False positive rate >80%",
            ],
            retrieval_tags=["transaction_monitoring", "aml", "alert"],
            corpus_hints=["Transaction monitoring", "Alert procedure", "MAS Notice 626", "Suspicious activity"],
            source_types=["SYSTEM_CONFIG", "PROCEDURE_DOCUMENT", "ALERT_SAMPLE"],
        ),
        JurisdictionControl(
            control_id="SG-AML-05",
            control_name="Suspicious Activity Reporting (SAR) to MAS - 15-Day Filing Requirement",
            control_description="Financial institution must file Suspicious Activity Report (SAR) with MAS within 15 days of detecting suspicious activity per MAS Notice 626 Section 36 and PMLT Act Section 39. SAR must include customer information, transaction details, and investigation findings. Institution must maintain SAR documentation and respond to MAS inquiries.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 36; PMLT Act Section 39",
            severity=Severity.CRITICAL,
            regulatory_reference="MAS Notice 626 Section 36; PMLT Act 2002 Section 39; MAS RMCD 3.1 paragraph 3.17",
            risk_if_missing="Failure to report suspicious activities, regulatory enforcement, financial penalties, criminal liability.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="SAR_POLICY",
                    description="Written SAR policy per MAS Notice 626 Section 36 with filing requirements and 15-day timeline",
                    scoring_keywords=[
                        "SAR policy",
                        "suspicious activity report",
                        "MAS Notice 626 Section 36",
                        "15-day filing",
                        "PMLT Act Section 39",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SAR_SAMPLES",
                    description="Sample SARs filed with MAS showing investigation findings and MAS filing confirmation",
                    scoring_keywords=[
                        "SAR",
                        "filed with MAS",
                        "SAR confirmation",
                        "suspicious activity report",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SAR_TRACKING",
                    description="SAR tracking log documenting filing dates, subjects, and MAS acknowledgments",
                    scoring_keywords=[
                        "SAR tracking",
                        "filing log",
                        "SAR record",
                        "acknowledgment",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Establish SAR policy with clear 15-day filing requirement per MAS Notice 626 Section 36. Create SAR form per MAS template. Identify SAR officer responsible for MAS submission. Establish MAS submission mechanism. Create tracking log. Train staff on SAR requirements and investigation process.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=20,
                    expected_evidence_after=["SAR_POLICY", "SAR_FORM", "TRACKING_LOG"],
                ),
            ],
            missing_criteria=[
                "No SAR policy documented",
                "No SARs filed despite suspicious activities",
                "No SAR tracking mechanism",
            ],
            partial_criteria=[
                "SARs filed but with delays exceeding 15 days",
                "SAR investigation incomplete",
                "No tracking of filed SARs",
            ],
            supported_criteria=[
                "SAR policy documented per MAS Notice 626 Section 36",
                "All suspicious activities escalated to SAR officer",
                "SARs filed within 15-day deadline",
                "Complete tracking and MAS acknowledgment maintained",
            ],
            risk_raise_criteria=[
                "SAR filing delays exceeding 15-day deadline",
                "No SARs filed despite alerts",
                "MAS follow-up on missing SARs",
            ],
            retrieval_tags=["sar", "suspicious_activity", "mas_reporting"],
            corpus_hints=["SAR filing", "Suspicious activity report", "MAS reporting", "PMLT Act"],
            source_types=["POLICY_DOCUMENT", "SAR_FORM", "TRACKING_LOG"],
        ),
        JurisdictionControl(
            control_id="SG-AML-06",
            control_name="Compliance Training and Staff Awareness Program",
            control_description="Financial institution must provide mandatory AML/CFT training per MAS Notice 626 Section 41 to all staff involved in customer relationships, transactions, and compliance. Training must cover CDD, EDD, transaction monitoring, SAR procedures, and sanctions compliance. Training provided at onboarding and annually.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 41; PMLT Act Section 36(1)(c)",
            severity=Severity.HIGH,
            regulatory_reference="MAS Notice 626 Section 41; PMLT Act Section 36(1)(c); MAS RMCD 3.1 paragraph 3.24",
            risk_if_missing="Staff unable to identify suspicious activities, poor compliance culture, regulatory enforcement.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="TRAINING_PROGRAM",
                    description="Written training program per MAS Notice 626 Section 41 covering AML/CFT requirements, CDD, EDD, monitoring, and SAR",
                    scoring_keywords=[
                        "training program",
                        "AML training",
                        "CFT training",
                        "MAS Notice 626 Section 41",
                        "curriculum",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="TRAINING_RECORDS",
                    description="Training attendance records showing all staff completed initial and annual training with signatures",
                    scoring_keywords=[
                        "training attendance",
                        "training record",
                        "staff training",
                        "completion",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop AML/CFT training program per MAS Notice 626 Section 41. Schedule onboarding training for all staff. Create annual refresher training. Implement attendance tracking. Maintain completion records. Document training content. Track attendance.",
                    owner_type="HR_COMPLIANCE",
                    priority="HIGH",
                    estimated_effort_days=15,
                    expected_evidence_after=["TRAINING_PROGRAM", "ATTENDANCE_RECORDS"],
                ),
            ],
            missing_criteria=[
                "No training program documented",
                "No training conducted",
                "No attendance records",
            ],
            partial_criteria=[
                "Training conducted but not annual",
                "Some staff not trained",
            ],
            supported_criteria=[
                "Comprehensive training program per MAS Notice 626 Section 41",
                "All staff trained at onboarding and annually",
                "Complete attendance records maintained",
            ],
            risk_raise_criteria=[
                "Staff with no training records",
                "Annual training not conducted",
            ],
            retrieval_tags=["training", "compliance", "aml_awareness"],
            corpus_hints=["Training program", "Staff training", "AML awareness", "MAS Notice 626"],
            source_types=["TRAINING_PROGRAM", "ATTENDANCE_LOG"],
        ),
        JurisdictionControl(
            control_id="SG-AML-07",
            control_name="Internal Audit and AML/CFT Program Review",
            control_description="Financial institution must conduct independent internal audit of AML/CFT program at least annually per MAS Notice 626 Section 42. Audit must assess policy compliance, control effectiveness, transaction monitoring, and SAR procedures. Findings must be documented and remediated within defined timelines. Board must be informed of audit results.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 42; PMLT Act Section 36(1)(d)",
            severity=Severity.HIGH,
            regulatory_reference="MAS Notice 626 Section 42; PMLT Act Section 36(1)(d); MAS RMCD 3.1 paragraph 3.25",
            risk_if_missing="Undetected AML/CFT control weaknesses, regulatory enforcement, financial penalties.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="AUDIT_PLAN",
                    description="Annual audit plan per MAS Notice 626 Section 42 documenting AML/CFT audit scope and procedures",
                    scoring_keywords=[
                        "audit plan",
                        "internal audit",
                        "AML audit",
                        "MAS Notice 626 Section 42",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="AUDIT_REPORT",
                    description="Internal audit report with findings and remediation tracking",
                    scoring_keywords=[
                        "audit report",
                        "internal audit",
                        "findings",
                        "remediation",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="BOARD_REPORT",
                    description="Board reporting of audit findings and management response per MAS Notice 626 Section 42",
                    scoring_keywords=[
                        "board report",
                        "management response",
                        "remediation plan",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Establish annual internal audit program per MAS Notice 626 Section 42. Engage internal audit or external auditor. Define scope. Document findings and management responses. Report to board. Track remediation with timelines.",
                    owner_type="AUDIT_FUNCTION",
                    priority="HIGH",
                    estimated_effort_days=25,
                    expected_evidence_after=["AUDIT_PLAN", "AUDIT_REPORT"],
                ),
            ],
            missing_criteria=[
                "No internal audit conducted",
                "No documented findings",
                "No remediation tracking",
            ],
            partial_criteria=[
                "Audit conducted but findings not documented",
                "Audit not conducted annually",
            ],
            supported_criteria=[
                "Annual audit plan per MAS Notice 626 Section 42",
                "Audit performed by independent function",
                "Findings documented with recommendations",
                "Board informed of results",
            ],
            risk_raise_criteria=[
                "No audit conducted in past 12 months",
                "Audit findings not remediated",
            ],
            retrieval_tags=["audit", "aml", "internal_audit"],
            corpus_hints=["Internal audit", "Audit report", "AML audit", "MAS Notice 626"],
            source_types=["AUDIT_PLAN", "AUDIT_REPORT"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # SANCTIONS DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="SG-SANCTIONS-01",
            control_name="Sanctions Screening - UN, Singapore, and Regional Lists",
            control_description="Financial institution must screen all customers and transactions against UN Security Council sanctions list, Singapore Ministry of Home Affairs consolidated list, and ASEAN/regional sanctions lists. Screening must occur at customer onboarding and continuously. Positive matches must be escalated immediately to compliance officer.",
            domain=Domain.SANCTIONS,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 9; United Nations Security Council Resolutions; Singapore Regulation of Imports and Exports Regulations",
            severity=Severity.CRITICAL,
            regulatory_reference="MAS Notice 626 Section 9; UN Security Council Resolutions; Singapore MHA Consolidated List; ASEAN Heads of Government Agreements",
            risk_if_missing="Sanctions violations, criminal liability, financial penalties, license revocation.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="SANCTIONS_SCREENING_SYSTEM",
                    description="Automated sanctions screening system with daily updates from UN, Singapore MHA, and ASEAN lists",
                    scoring_keywords=[
                        "sanctions screening",
                        "UN sanctions",
                        "Singapore MHA list",
                        "automated screening",
                        "sanctions list",
                    ],
                    confidence_threshold=0.95,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SCREENING_PROCEDURE",
                    description="Procedure documenting sanctions screening, positive match escalation, and investigation",
                    scoring_keywords=[
                        "screening procedure",
                        "sanctions procedure",
                        "positive match",
                        "escalation process",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SCREENING_LOG",
                    description="Screening log documenting dates screened, lists checked, and clearance for all customers",
                    scoring_keywords=[
                        "screening log",
                        "screening record",
                        "clearance documentation",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement automated sanctions screening system with daily updates from UN, Singapore MHA, and ASEAN lists. Establish positive match escalation to compliance officer. Screen all customers at onboarding and monthly. Document clearance. Create escalation tracking log.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=40,
                    expected_evidence_after=["SCREENING_SYSTEM", "PROCEDURE", "SCREENING_LOG"],
                ),
            ],
            missing_criteria=[
                "No sanctions screening system",
                "Customers not screened against UN/Singapore lists",
                "No ongoing transaction screening",
            ],
            partial_criteria=[
                "Screening system exists but not comprehensive",
                "Lists not updated daily",
                "Positive matches not escalated promptly",
            ],
            supported_criteria=[
                "Automated screening with UN/Singapore/ASEAN lists",
                "All customers screened at onboarding and monthly",
                "Lists updated daily minimum",
                "Positive matches escalated within 4 hours",
            ],
            risk_raise_criteria=[
                "Lists not updated in past 24 hours",
                "Customer screened >30 days ago without update",
                "Positive match without escalation",
            ],
            retrieval_tags=["sanctions", "un_sanctions", "screening"],
            corpus_hints=["Sanctions screening", "UN sanctions", "Singapore MHA list", "Screening system"],
            source_types=["SYSTEM_CONFIG", "PROCEDURE_DOCUMENT", "SCREENING_LOG"],
        ),
        JurisdictionControl(
            control_id="SG-SANCTIONS-02",
            control_name="Sanctions Compliance - Transaction Blocking and Reporting",
            control_description="Financial institution must implement transaction controls per MAS Notice 626 Section 9 to prevent transfers to/from sanctioned parties. System must block transactions to sanctioned parties. For ambiguous cases, must escalate to compliance and legal team. Blocked transactions must be documented and reported to MAS if applicable.",
            domain=Domain.SANCTIONS,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 9; Regulation of Imports and Exports (Finance) Regulations",
            severity=Severity.CRITICAL,
            regulatory_reference="MAS Notice 626 Section 9; United Nations Security Council Resolutions; Singapore Regulation of Imports and Exports Regulations",
            risk_if_missing="Sanctions violations, criminal liability, financial penalties, license revocation.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="TRANSACTION_BLOCKING_CONFIG",
                    description="System configuration with transaction blocking rules integrated with sanctions screening",
                    scoring_keywords=[
                        "transaction blocking",
                        "blocking rules",
                        "transaction control",
                        "filtering",
                    ],
                    confidence_threshold=0.90,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="BLOCKED_TRANSACTION_LOG",
                    description="Log of blocked transactions with dates, parties, reasons, and escalation outcomes",
                    scoring_keywords=[
                        "blocked transaction",
                        "blocking log",
                        "blocked transfer",
                    ],
                    confidence_threshold=0.90,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement transaction filtering integrated with sanctions screening. Configure system to block transactions to flagged parties. Establish escalation for borderline cases. Maintain blocked transaction log. Prepare MAS reporting for applicable incidents.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=30,
                    expected_evidence_after=["BLOCKING_CONFIG", "BLOCKED_LOG"],
                ),
            ],
            missing_criteria=[
                "No transaction filtering system",
                "Transactions to sanctioned parties not blocked",
            ],
            partial_criteria=[
                "Filtering exists but incomplete",
                "Blocked transactions not documented",
            ],
            supported_criteria=[
                "Automated filtering integrated with sanctions screening",
                "All transactions blocked appropriately",
                "Complete documentation of blocked transactions",
            ],
            risk_raise_criteria=[
                "Transaction processed to sanctioned party",
                "No blocked transaction log",
            ],
            retrieval_tags=["sanctions", "transaction_blocking"],
            corpus_hints=["Transaction blocking", "Sanctions compliance", "Blocked transactions"],
            source_types=["SYSTEM_CONFIG", "TRANSACTION_LOG"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # FRAUD DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="SG-FRAUD-01",
            control_name="Fraud Detection and Prevention Systems",
            control_description="Financial institution must implement fraud detection systems to identify anomalous transaction patterns and account compromise indicators. System must monitor for velocity abuse, unusual geographic patterns, and deviation from customer behavior baseline. Alerts must trigger manual review and investigation.",
            domain=Domain.FRAUD_TXN_MONITORING,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS RMCD Chapter 4 (Technology Risk); Payment Systems (Domestic) Regulations 2005",
            severity=Severity.HIGH,
            regulatory_reference="MAS RMCD Chapter 4 (Technology Risk); Payment Systems (Domestic) Regulations 2005",
            risk_if_missing="Undetected fraud, financial losses, customer trust erosion, regulatory enforcement.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="FRAUD_DETECTION_SYSTEM",
                    description="Fraud detection system documentation including rules, thresholds, and performance metrics",
                    scoring_keywords=[
                        "fraud detection",
                        "anomaly detection",
                        "fraud system",
                        "fraud rules",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="FRAUD_ALERTS",
                    description="Sample fraud alerts with investigation outcomes and resolution",
                    scoring_keywords=[
                        "fraud alert",
                        "fraud investigation",
                        "suspicious transaction",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement fraud detection system with velocity abuse, unusual pattern, and geographic anomaly rules. Establish alert investigation procedure. Create fraud investigation team. Monitor system performance. Train staff on fraud detection.",
                    owner_type="FRAUD_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=35,
                    expected_evidence_after=["FRAUD_SYSTEM", "ALERT_SAMPLES"],
                ),
            ],
            missing_criteria=[
                "No fraud detection system",
                "No fraud monitoring",
            ],
            partial_criteria=[
                "Fraud system exists but not comprehensive",
                "Alert investigation inconsistent",
            ],
            supported_criteria=[
                "Automated fraud detection with documented rules",
                "Alerts generated for suspicious patterns",
                "Timely investigation and resolution",
            ],
            risk_raise_criteria=[
                "High false positive rate (>85%)",
                "Alert backlog exceeding 30 days",
            ],
            retrieval_tags=["fraud_detection", "anomaly_detection"],
            corpus_hints=["Fraud detection", "Fraud prevention", "Anomaly detection", "Fraud system"],
            source_types=["SYSTEM_CONFIG", "ALERT_SAMPLE"],
        ),
        JurisdictionControl(
            control_id="SG-FRAUD-02",
            control_name="Fraud Investigation and Loss Recovery",
            control_description="Financial institution must establish procedures for investigating detected fraud, including victim notification, fund recovery attempts, and law enforcement reporting. Procedures must include evidence preservation, forensic investigation, and documentation of findings. Institution must maintain fraud loss records and identify trends.",
            domain=Domain.FRAUD_TXN_MONITORING,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS RMCD Chapter 4; Singapore Police Force Liaison",
            severity=Severity.HIGH,
            regulatory_reference="MAS RMCD Chapter 4; Singapore Penal Code Section 420 (Cheating); Singapore Police Force Cybercrime Unit",
            risk_if_missing="Unrecovered fraud losses, customer dissatisfaction, regulatory enforcement.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="FRAUD_INVESTIGATION_PROCEDURE",
                    description="Procedure for fraud investigation, victim notification, law enforcement reporting, and recovery",
                    scoring_keywords=[
                        "fraud investigation",
                        "investigation procedure",
                        "victim notification",
                        "law enforcement",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="INVESTIGATION_SAMPLES",
                    description="Sample investigation files showing case documentation and resolution",
                    scoring_keywords=[
                        "investigation file",
                        "case file",
                        "investigation report",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="FRAUD_LOSS_REGISTER",
                    description="Fraud loss register tracking incidents and recoveries",
                    scoring_keywords=[
                        "fraud loss",
                        "loss register",
                        "fraud tracking",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop fraud investigation procedure with victim notification, evidence preservation, and law enforcement reporting. Create investigation file template. Establish fraud loss register. Train investigators. Define law enforcement reporting triggers.",
                    owner_type="FRAUD_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=20,
                    expected_evidence_after=["PROCEDURE", "INVESTIGATION_TEMPLATE", "LOSS_REGISTER"],
                ),
            ],
            missing_criteria=[
                "No fraud investigation procedure",
                "No victim notification process",
                "No law enforcement reporting",
            ],
            partial_criteria=[
                "Procedure exists but incomplete",
                "Victim notification inconsistent",
            ],
            supported_criteria=[
                "Comprehensive investigation procedure documented",
                "Cases investigated within 5 business days",
                "Victims notified within 24 hours",
                "Law enforcement reports filed appropriately",
                "Fraud loss register maintained",
            ],
            risk_raise_criteria=[
                "Investigation delays exceeding 10 days",
                "Victim not notified",
                "Law enforcement not reported",
            ],
            retrieval_tags=["fraud_investigation", "incident_response"],
            corpus_hints=["Fraud investigation", "Incident response", "Victim notification", "Case file"],
            source_types=["PROCEDURE_DOCUMENT", "INVESTIGATION_FILE", "LOSS_REGISTER"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # GOVERNANCE DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="SG-GOV-01",
            control_name="Compliance Governance - Board Oversight and Independent Compliance Officer",
            control_description="Financial institution must establish governance structure per MAS RMCD 2.1 with designated compliance officer having adequate independence and access to board. Compliance officer must report directly to board audit committee. Board must oversee compliance status quarterly.",
            domain=Domain.GOVERNANCE_VENDOR,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS RMCD 2.1 (Governance & Compliance); MAS RMCD 3.2 (Compliance Officer)",
            severity=Severity.HIGH,
            regulatory_reference="MAS RMCD 2.1; MAS RMCD 3.2; MAS Guidelines on Fit and Proper Criteria",
            risk_if_missing="Weak compliance oversight, undetected control failures, regulatory enforcement, financial penalties.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="GOVERNANCE_CHARTER",
                    description="Board charter defining compliance officer role, reporting line, and independence per MAS RMCD 2.1",
                    scoring_keywords=[
                        "board charter",
                        "governance document",
                        "compliance officer",
                        "MAS RMCD 2.1",
                        "reporting line",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="BOARD_MINUTES",
                    description="Board minutes from past 12 months showing quarterly compliance reviews per MAS RMCD 2.1",
                    scoring_keywords=[
                        "board minutes",
                        "compliance review",
                        "board meeting",
                        "governance discussion",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="COMPLIANCE_OFFICER_AUTHORITY",
                    description="Documentation of compliance officer authority, budget, and direct reporting to board per MAS RMCD 3.2",
                    scoring_keywords=[
                        "compliance officer",
                        "authority document",
                        "MAS RMCD 3.2",
                        "reporting structure",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Establish governance structure per MAS RMCD 2.1. Designate compliance officer with adequate independence (not reporting to business line). Document role in governance charter. Assign adequate budget and staff. Establish quarterly board compliance reviews.",
                    owner_type="BOARD",
                    priority="HIGH",
                    estimated_effort_days=25,
                    expected_evidence_after=["CHARTER", "BOARD_MINUTES"],
                ),
            ],
            missing_criteria=[
                "No designated compliance officer",
                "Officer reports to business line head",
                "No board oversight",
            ],
            partial_criteria=[
                "Officer exists but insufficient resources",
                "Reporting line indirect",
                "Board review infrequent",
            ],
            supported_criteria=[
                "Designated officer with MAS RMCD independence",
                "Direct reporting to board/audit committee",
                "Quarterly board compliance reviews",
                "Governance charter defines roles",
            ],
            risk_raise_criteria=[
                "Officer reports to business head",
                "No board review in past 6 months",
            ],
            retrieval_tags=["governance", "compliance_officer", "board_oversight"],
            corpus_hints=["Board governance", "Compliance officer", "MAS RMCD", "Governance structure"],
            source_types=["CHARTER", "BOARD_MINUTES"],
        ),
        JurisdictionControl(
            control_id="SG-GOV-02",
            control_name="Regulatory Compliance and Filing Obligations",
            control_description="Financial institution must comply with all MAS regulatory filing obligations including periodic regulatory returns, compliance certifications, and incident reporting. Institution must maintain filing calendar and track submissions. Institution must respond to MAS inquiries and supervisory notices within required timelines.",
            domain=Domain.GOVERNANCE_VENDOR,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Regulatory Framework; MAS Notice Series",
            severity=Severity.HIGH,
            regulatory_reference="MAS Banking Regulation Framework; MAS Notice 626; MAS Reporting Framework",
            risk_if_missing="Missing regulatory reports, regulatory enforcement, financial penalties, license suspension.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="FILING_CALENDAR",
                    description="Calendar documenting all MAS regulatory filings with deadlines",
                    scoring_keywords=[
                        "filing calendar",
                        "regulatory filing",
                        "filing deadline",
                        "MAS reporting",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="FILING_CONFIRMATIONS",
                    description="Submission confirmations and receipts from MAS for past 12 months",
                    scoring_keywords=[
                        "filing confirmation",
                        "submission receipt",
                        "MAS filing",
                        "confirmation letter",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SUPERVISORY_CORRESPONDENCE",
                    description="Log of MAS letters, information requests, and responses",
                    scoring_keywords=[
                        "MAS letter",
                        "information request",
                        "supervisory correspondence",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Create regulatory filing calendar with all MAS requirements and deadlines. Identify responsible parties. Establish submission process. Create log to track submissions and confirmations. Set automated reminders.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=15,
                    expected_evidence_after=["FILING_CALENDAR", "FILING_LOG"],
                ),
            ],
            missing_criteria=[
                "No filing calendar",
                "Regulatory filings missed or late",
            ],
            partial_criteria=[
                "Calendar exists but incomplete",
                "Filings submitted but occasionally late",
            ],
            supported_criteria=[
                "Comprehensive filing calendar maintained",
                "All filings submitted on time",
                "Confirmations tracked and filed",
                "MAS inquiries responded to within 20 days",
            ],
            risk_raise_criteria=[
                "Filing submitted late",
                "Missing filing confirmation",
                "MAS notice regarding compliance",
            ],
            retrieval_tags=["regulatory_filing", "mas_compliance"],
            corpus_hints=["Regulatory filing", "MAS reporting", "Filing calendar", "Supervisory communication"],
            source_types=["FILING_CALENDAR", "CONFIRMATION", "FILING_LOG"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # LICENSING AND FILINGS DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="SG-LIC-01",
            control_name="Financial Services License and Regulatory Authorization",
            control_description="Financial institution must obtain and maintain valid license from MAS for all regulated financial services activities. License must be current and displayed. Institution must notify MAS of any material changes to operations, ownership, or senior management within specified timelines.",
            domain=Domain.LICENSING_FILINGS,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="Banking Act; Securities and Futures Act; Payment Systems (Domestic) Regulations 2005",
            severity=Severity.CRITICAL,
            regulatory_reference="Banking Act (Cap. 19); Securities and Futures Act (Cap. 289); Payment Systems (Domestic) Regulations 2005",
            risk_if_missing="Unauthorized operation, regulatory enforcement, license revocation, criminal liability.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="LICENSE_CERTIFICATE",
                    description="Valid MAS license certificate showing license number, scope, and validity period",
                    scoring_keywords=[
                        "MAS license",
                        "license certificate",
                        "regulatory license",
                        "authorization",
                        "license number",
                    ],
                    confidence_threshold=0.95,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="AUTHORIZATION_LETTER",
                    description="MAS authorization letter detailing licensed activities and conditions",
                    scoring_keywords=[
                        "authorization letter",
                        "license letter",
                        "MAS authorization",
                        "license conditions",
                    ],
                    confidence_threshold=0.95,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="LICENSE_RENEWAL",
                    description="Evidence of current license status and renewal confirmation within past 12 months",
                    scoring_keywords=[
                        "license renewal",
                        "renewal confirmation",
                        "current license",
                        "valid license",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Apply for MAS financial services license. Prepare application with governance documentation, business plan, financial statements. Submit with required fees. Obtain license approval letter. Display license certificate. Establish renewal calendar.",
                    owner_type="BOARD",
                    priority="CRITICAL",
                    estimated_effort_days=120,
                    expected_evidence_after=["LICENSE_CERT", "AUTH_LETTER"],
                ),
            ],
            missing_criteria=[
                "No valid MAS license",
                "Operating without authorization",
                "License expired",
            ],
            partial_criteria=[
                "License scope limited",
                "Renewal process started",
            ],
            supported_criteria=[
                "Valid MAS license for all activities",
                "License displayed conspicuously",
                "Renewal confirmed within 12 months",
            ],
            risk_raise_criteria=[
                "License expired",
                "Renewal not processed",
                "Regulatory notice regarding status",
            ],
            retrieval_tags=["license", "mas_authorization"],
            corpus_hints=["MAS license", "Regulatory license", "Authorization", "Banking Act"],
            source_types=["LICENSE_CERTIFICATE", "AUTHORIZATION_LETTER"],
        ),
        JurisdictionControl(
            control_id="SG-LIC-02",
            control_name="License Condition Compliance and Material Change Reporting",
            control_description="Financial institution must comply with all conditions specified in MAS license. Institution must notify MAS of material changes within required timelines including change of ownership, senior management, business lines, or location. Notification must be accompanied by updated documentation.",
            domain=Domain.LICENSING_FILINGS,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="Banking Act Section 22A; Securities and Futures Act Section 77G; MAS Regulatory Framework",
            severity=Severity.HIGH,
            regulatory_reference="Banking Act Section 22A; Securities and Futures Act Section 77G; MAS Regulatory Framework; MAS Notice Series",
            risk_if_missing="License violation, regulatory enforcement, license suspension/revocation.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="LICENSE_CONDITIONS",
                    description="Documented list of license conditions with compliance status",
                    scoring_keywords=[
                        "license conditions",
                        "compliance conditions",
                        "license requirements",
                        "license terms",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="CHANGE_NOTIFICATION",
                    description="Material change notifications submitted to MAS with supporting documentation",
                    scoring_keywords=[
                        "change notification",
                        "material change",
                        "MAS notification",
                        "ownership change",
                        "management change",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="COMPLIANCE_MONITORING",
                    description="Log showing regular review of license conditions and compliance confirmation",
                    scoring_keywords=[
                        "compliance monitoring",
                        "condition monitoring",
                        "compliance check",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Extract all conditions from MAS authorization letter. Create compliance checklist. Establish material change identification process. Implement MAS notification procedure with required documentation. Create change notification log. Establish annual compliance review.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=15,
                    expected_evidence_after=["CONDITIONS_LIST", "CHANGE_NOTIFICATION_LOG"],
                ),
            ],
            missing_criteria=[
                "License conditions not documented",
                "Material changes not reported to MAS",
            ],
            partial_criteria=[
                "Conditions documented but not monitored",
                "Change notifications submitted late",
            ],
            supported_criteria=[
                "All conditions documented and monitored",
                "Material changes reported within required timelines",
                "Documentation includes supporting materials",
            ],
            risk_raise_criteria=[
                "Unreported material change",
                "License condition violation",
                "MAS notice regarding compliance",
            ],
            retrieval_tags=["license_compliance", "material_change"],
            corpus_hints=["License conditions", "Material change", "MAS notification", "Compliance monitoring"],
            source_types=["CONDITION_LIST", "CHANGE_NOTIFICATION"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # PRIVACY AND DATA PROTECTION DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="SG-PRIVACY-01",
            control_name="Personal Data Protection Policy - PDPA Compliance",
            control_description="Financial institution must establish privacy policy per Personal Data Protection Act (PDPA) covering collection, use, retention, and sharing of personal data. Policy must describe customer rights and be published. Institution must obtain customer consent for data processing and implement access/correction procedures.",
            domain=Domain.PRIVACY_DATA,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.PDPC,
            regime_mapping="Personal Data Protection Act (PDPA) 2012; PDPC Advisory Guidelines; Singapore Data Protection Framework",
            severity=Severity.HIGH,
            regulatory_reference="Personal Data Protection Act (PDPA) 2012 Sections 17-18; PDPC Advisory Guidelines on Consent and Notification; PDPC Guidelines on Personal Data Protection",
            risk_if_missing="Unauthorized data use, PDPA violations, PDPC enforcement, financial penalties, customer complaints.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="PRIVACY_POLICY",
                    description="Written privacy policy per PDPA Section 17 published and provided to customers",
                    scoring_keywords=[
                        "privacy policy",
                        "PDPA",
                        "data protection",
                        "PDPA Section 17",
                        "privacy notice",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="CONSENT_MECHANISM",
                    description="Documented consent mechanism per PDPA Section 13 for data processing",
                    scoring_keywords=[
                        "consent",
                        "data consent",
                        "PDPA Section 13",
                        "consent form",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="DATA_ACCESS_PROCEDURE",
                    description="Procedure allowing customers to access, correct, or request deletion per PDPA Sections 19-20",
                    scoring_keywords=[
                        "data access",
                        "customer access",
                        "data correction",
                        "PDPA Section 19",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop PDPA-compliant privacy policy per Section 17. Describe data collection, use, retention, and sharing. Publish on website. Implement consent mechanism per Section 13. Create data access/correction request procedure per Sections 19-20. Train staff on PDPA requirements.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=20,
                    expected_evidence_after=["PRIVACY_POLICY", "CONSENT_FORM"],
                ),
            ],
            missing_criteria=[
                "No privacy policy per PDPA",
                "No customer consent process",
                "Data handling not documented",
            ],
            partial_criteria=[
                "Policy exists but not PDPA aligned",
                "Consent process not systematic",
            ],
            supported_criteria=[
                "Comprehensive PDPA-compliant privacy policy",
                "Consent obtained per PDPA Section 13",
                "Data access/correction procedures per Sections 19-20",
                "Regular policy review and updates",
            ],
            risk_raise_criteria=[
                "Privacy policy not published",
                "Customer consent not documented",
                "Data access request not processed",
            ],
            retrieval_tags=["privacy", "pdpa", "data_protection"],
            corpus_hints=["Privacy policy", "PDPA", "Data protection", "Consent"],
            source_types=["PRIVACY_POLICY", "CONSENT_FORM"],
        ),
        JurisdictionControl(
            control_id="SG-PRIVACY-02",
            control_name="Data Security and Breach Notification - PDPA Compliance",
            control_description="Financial institution must implement data security controls per PDPA Section 24 to protect personal data from unauthorized access, disclosure, or loss. Institution must maintain breach register and notify affected individuals and PDPC of data breaches without undue delay. Institution must conduct security assessments.",
            domain=Domain.PRIVACY_DATA,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.PDPC,
            regime_mapping="Personal Data Protection Act (PDPA) 2012 Sections 24-25; PDPC Guidelines on Data Protection Measures; PDPC Breach Notification Guidelines",
            severity=Severity.HIGH,
            regulatory_reference="PDPA 2012 Sections 24-25; PDPC Guidelines on Data Protection Measures; PDPC Guidelines on Breach Notification; Singapore Cybersecurity Act 2018",
            risk_if_missing="Data breaches, PDPA enforcement, PDPC fines, customer data theft, reputational damage.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="DATA_SECURITY_POLICY",
                    description="Data security policy per PDPA Section 24 specifying encryption, access control, and audit trail measures",
                    scoring_keywords=[
                        "data security",
                        "PDPA Section 24",
                        "encryption",
                        "access control",
                        "security policy",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SECURITY_ASSESSMENT",
                    description="Annual security assessment or penetration test report per PDPA Section 24",
                    scoring_keywords=[
                        "security assessment",
                        "penetration test",
                        "PDPA Section 24",
                        "security audit",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="BREACH_REGISTER",
                    description="Breach register per PDPC guidelines with breach details and notification evidence",
                    scoring_keywords=[
                        "breach register",
                        "breach notification",
                        "PDPC notification",
                        "breach log",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop data security policy per PDPA Section 24 with encryption (AES-256 at rest, TLS in transit), role-based access, audit trails. Implement controls and conduct annual security assessment. Establish breach response procedure with notification to affected individuals and PDPC without undue delay. Create breach register.",
                    owner_type="CISO",
                    priority="HIGH",
                    estimated_effort_days=40,
                    expected_evidence_after=["SECURITY_POLICY", "ASSESSMENT_REPORT", "BREACH_REGISTER"],
                ),
            ],
            missing_criteria=[
                "No data security policy per PDPA Section 24",
                "No encryption controls",
                "No breach response procedure",
                "No breach register",
            ],
            partial_criteria=[
                "Security controls exist but not comprehensive",
                "No annual security assessment",
                "Breach notification delays",
            ],
            supported_criteria=[
                "Comprehensive security policy per PDPA Section 24",
                "Encryption at rest and in transit",
                "Annual security assessments",
                "Breach register maintained",
                "Timely breach notification to individuals and PDPC",
            ],
            risk_raise_criteria=[
                "Data breach not reported to PDPC",
                "Unencrypted sensitive data",
                "No audit trail for access",
            ],
            retrieval_tags=["data_security", "breach_notification", "pdpa"],
            corpus_hints=["Data security", "PDPA", "Breach notification", "Security policy"],
            source_types=["SECURITY_POLICY", "ASSESSMENT_REPORT", "BREACH_REGISTER"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # REAL ESTATE DOMAIN (1 CONTROL)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="SG-RE-01",
            control_name="Real Estate Transaction Compliance - Property Financing and Beneficial Ownership per MAS Notice 626",
            control_description="Financial institution providing real estate financing must conduct enhanced due diligence per MAS Notice 626 Section 9 on property transactions. Procedures must verify beneficial ownership of property, source of down payment funds, and assess transaction risk for ML/TF indicators. For commercial real estate, verify ultimate beneficial owners. Maintain transaction documentation.",
            domain=Domain.REAL_ESTATE,
            jurisdiction=JurisdictionCode.SG,
            regulator=Regulator.MAS,
            regime_mapping="MAS Notice 626 Section 9 (EDD); MAS RMCD 3.1 (Real Estate Risk); FATF Real Estate Risk Guidance",
            severity=Severity.HIGH,
            regulatory_reference="MAS Notice 626 Section 9; MAS RMCD 3.1 paragraphs 3.9-3.15; FATF Real Estate Evaluation Guidance; Singapore Land Authority Guidelines",
            risk_if_missing="Real estate used for money laundering, sanctions evasion, regulatory enforcement, financial penalties.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="RE_FINANCING_PROCEDURE",
                    description="Real estate financing procedure per MAS Notice 626 Section 9 with beneficial ownership verification and source of funds checks",
                    scoring_keywords=[
                        "real estate",
                        "property financing",
                        "beneficial ownership",
                        "MAS Notice 626 Section 9",
                        "source of funds",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="RE_TRANSACTION_SAMPLE",
                    description="Sample real estate files showing beneficial ownership documentation and source of funds verification",
                    scoring_keywords=[
                        "real estate file",
                        "property file",
                        "beneficial owner",
                        "source of funds",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="TRANSACTION_REGISTRY",
                    description="Real estate transaction registry with beneficial owner identification and property details",
                    scoring_keywords=[
                        "transaction registry",
                        "real estate registry",
                        "property register",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop real estate procedure per MAS Notice 626 Section 9. Require beneficial ownership verification via HDB/Land Authority/property records. Verify source of funds for down payment >SGD 50K. Assess transaction risk for ML/TF red flags. For commercial property, verify UBO per Section 9. Maintain transaction registry.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=30,
                    expected_evidence_after=["RE_PROCEDURE", "TRANSACTION_FILES"],
                ),
            ],
            missing_criteria=[
                "No real estate procedure per MAS Notice 626",
                "Beneficial owner not verified for property",
                "Source of funds not verified",
            ],
            partial_criteria=[
                "Procedure exists but not MAS-aligned",
                "Beneficial ownership verification incomplete",
            ],
            supported_criteria=[
                "Real estate procedure per MAS Notice 626 Section 9",
                "Source of funds verified for down payments >SGD 50K",
                "Property registry cross-checks conducted",
                "Commercial property UBO verification completed",
                "Transaction registry maintained",
            ],
            risk_raise_criteria=[
                "Property financed without beneficial owner verification",
                "Unusual property price not questioned",
                "Commercial property without UBO verification",
            ],
            real_estate_overlays=[
                RealEstateOverlay(
                    scenario="Residential HDB/Condo - Singapore Resident Buyer",
                    kyc_expectations="Identity verification per MAS Notice 626 Section 8, source of funds verification for down payment >SGD 50K, residence address verification, employment verification, no PEP screening required unless property value >SGD 2M or buyer identified as PEP",
                    source_of_funds_check=True,
                    beneficial_ownership_depth=1,
                    transaction_red_flags=[
                        "Funding from third party without clear relationship",
                        "Gift from non-Singapore source without documentation",
                        "Structuring (multiple transfers <SGD 50K each)",
                        "Cash down payment >SGD 10K",
                    ],
                    sector_specific_risks=[
                        "CPF withdrawal irregularities (CPF Board has caps on withdrawals)",
                        "Housing loan that exceeds bank lending limits",
                        "Refinancing with unusually high valuations",
                    ],
                ),
                RealEstateOverlay(
                    scenario="Commercial Property - Corporate Buyer (Singapore Registered)",
                    kyc_expectations="Ultimate beneficial owner identification per MAS Notice 626 Section 9, company ACRA registry verification, corporate structure analysis, beneficial owner identity verification and PEP/sanctions screening, board resolution for purchase authorization, financing source verification",
                    source_of_funds_check=True,
                    beneficial_ownership_depth=3,
                    transaction_red_flags=[
                        "Shell company without clear business purpose",
                        "Rapid property transfer between entities within 12 months",
                        "Non-ASEAN financing source",
                        "UBO identity concealment through nominees",
                    ],
                    sector_specific_risks=[
                        "Commercial property collateral for project financing",
                        "Transfer pricing issues between related entities",
                        "Property rental at below-market rates to affiliate",
                    ],
                ),
                RealEstateOverlay(
                    scenario="Developer/Investment - Large Property Project (>SGD 10M)",
                    kyc_expectations="Developer source of funds verification, investor beneficial ownership per MAS Notice 626 Section 9, project financing verification, anti-corruption checks for government approvals (planning permission, land acquisition)",
                    source_of_funds_check=True,
                    beneficial_ownership_depth=2,
                    transaction_red_flags=[
                        "Funding from non-ASEAN jurisdiction",
                        "Investor UBO identity concealment",
                        "Rapid property price changes in short period",
                        "Large cash deposits to project account (>SGD 100K)",
                    ],
                    sector_specific_risks=[
                        "Development project used as cover for money laundering",
                        "Corruption in planning and land acquisition process",
                        "Financing from proceeds of corruption/bribery",
                        "Real estate speculation with complex entity structures",
                    ],
                ),
                RealEstateOverlay(
                    scenario="Cross-Border Property - Non-Singapore Resident Purchaser",
                    kyc_expectations="Enhanced due diligence per MAS Notice 626 Section 9, country-specific risk assessment (FATF grey list check), source of funds from non-Singapore jurisdiction, beneficial owner verification and PEP/sanctions screening, FATF recommendation compliance assessment",
                    source_of_funds_check=True,
                    beneficial_ownership_depth=2,
                    transaction_red_flags=[
                        "Non-resident from high-risk jurisdiction",
                        "Source of funds difficult to verify",
                        "Complex non-Singapore financing structure",
                        "Beneficial owner unwilling to provide documentation",
                        "All-cash property purchase",
                    ],
                    sector_specific_risks=[
                        "Non-resident laundering proceeds through Singapore property market",
                        "Political exposure/PEP using Singapore property for capital flight",
                        "Trade-based money laundering through property valuation",
                        "Singapore property as collateral for non-ASEAN structured finance",
                    ],
                ),
            ],
            retrieval_tags=["real_estate", "property_financing", "mas_notice_626"],
            corpus_hints=["Real estate", "Property financing", "MAS Notice 626", "Beneficial owner"],
            source_types=["RE_PROCEDURE", "TRANSACTION_FILE", "PROPERTY_REGISTRY"],
        ),
    ],
)
