"""
UAE Jurisdiction Pack v1 — 18 comprehensive compliance controls.
Bible §11.6 — UAE jurisdiction-specific compliance framework.

Domains:
- AML/KYC (7 controls): UAE-AML-01 through UAE-AML-07
- SANCTIONS (2 controls): UAE-SANCTIONS-01, UAE-SANCTIONS-02
- FRAUD (2 controls): UAE-FRAUD-01, UAE-FRAUD-02
- GOVERNANCE (2 controls): UAE-GOV-01, UAE-GOV-02
- LICENSING (2 controls): UAE-LIC-01, UAE-LIC-02
- PRIVACY (2 controls): UAE-PRIVACY-01, UAE-PRIVACY-02
- REAL ESTATE (1 control): UAE-RE-01

Regulators: CBUAE (Central Bank), DFSA (Dubai FSA), ADGM, DIFC
Effective: 2026-01-01
"""

from app.agents.jurisdiction_types import (
    JurisdictionControl,
    JurisdictionPackMetadata,
    JurisdictionPack,
    Domain,
    JurisdictionCode,
    Regulator,
    Severity,
    EvidenceRequirement,
    RemediationTemplate,
    RealEstateOverlay,
)


UAE_PACK_V1 = JurisdictionPack(
    metadata=JurisdictionPackMetadata(
        pack_id="UAE-v1",
        jurisdiction=JurisdictionCode.UAE,
        country_codes=["AE"],
        regulators=[
            Regulator.CBUAE,
            Regulator.DFSA,
            Regulator.ADGM,
            Regulator.DIFC,
        ],
        domains=[
            Domain.AML_KYC,
            Domain.SANCTIONS,
            Domain.FRAUD_TXN_MONITORING,
            Domain.GOVERNANCE_VENDOR,
            Domain.LICENSING_FILINGS,
            Domain.PRIVACY_DATA,
            Domain.REAL_ESTATE,
        ],
        version="1.0",
        source_references=[
            "https://www.cbuae.ae/en/regulation/financial-crime/aml-cft",
            "https://www.dfsa.ae/en/Regulatory-Framework/AML-CFT",
            "https://www.adgm.com/en/regulated-activities/aml-cft",
            "https://www.difc.ae/en/register/registers/anti-money-laundering",
        ],
        effective_date="2026-01-01",
        priority=2,
        applicability_notes="Mandatory for all UAE-based entities and foreign entities operating in UAE. ADGM/DIFC entities subject to additional overlay requirements.",
    ),
    controls=[
        # ═════════════════════════════════════════════════════════════════════════
        # AML/KYC DOMAIN (7 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="UAE-AML-01",
            control_name="AML/CFT Program - Comprehensive Policy Framework",
            control_description="Financial institution must establish written AML/CFT program approved by board of directors. Program must address customer due diligence (CDD), enhanced due diligence (EDD), beneficial ownership identification, transaction monitoring, suspicious activity reporting (SAR), and record keeping. Must comply with CBUAE Module 5.1 and DFSA rulebook.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Module 5.1 (AML/CFT) v5.0; DFSA Rulebook Module 5 AML/CFT",
            severity=Severity.CRITICAL,
            regulatory_reference="CBUAE Circular No. 144/2024; DFSA Rulebook AML Module 5.1; UAE Federal Law No. 20/2018",
            risk_if_missing="Regulatory enforcement, monetary penalties AED 500K-5M, operating license suspension/revocation, reputational damage, criminal liability for management.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="AML_POLICY",
                    description="Board-approved written AML/CFT policy with clear governance structure and management roles",
                    scoring_keywords=[
                        "anti-money laundering",
                        "counter terrorism financing",
                        "AML/CFT program",
                        "board approval",
                        "CBUAE Module 5.1",
                        "DFSA rulebook",
                        "written policy",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                    examples=["AML_CFT_Policy_2024.pdf", "Board_Resolution_AML_Approval.docx"],
                ),
                EvidenceRequirement(
                    document_type="CDD_PROCEDURES",
                    description="Documented CDD procedures including customer identification, nationality verification, and UBO identification",
                    scoring_keywords=[
                        "customer due diligence",
                        "CDD procedures",
                        "know your customer",
                        "beneficial owner",
                        "identification",
                        "verification",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="TRANSACTION_MONITORING",
                    description="Automated transaction monitoring system specifications with alert thresholds and escalation procedures",
                    scoring_keywords=[
                        "transaction monitoring",
                        "suspicious activity",
                        "alert system",
                        "monitoring rules",
                        "threshold",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SAR_PROCEDURES",
                    description="Suspicious Activity Reporting (SAR) procedures with timelines and escalation to CBUAE/DFSA",
                    scoring_keywords=[
                        "suspicious activity report",
                        "SAR",
                        "reporting procedures",
                        "CBUAE reporting",
                        "financial crime",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop comprehensive written AML/CFT program with board approval. Document CDD procedures, transaction monitoring rules, and SAR protocols. Establish governance structure with compliance officer and audit functions. Conduct staff training. Implement technology controls.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=60,
                    expected_evidence_after=["AML_POLICY", "PROCEDURES", "TRAINING_RECORDS", "SYSTEM_CONFIG"],
                ),
                RemediationTemplate(
                    gap_type="PARTIAL",
                    corrective_action="Review existing AML program against CBUAE Module 5.1 and DFSA requirements. Update policy documentation, enhance EDD procedures, strengthen transaction monitoring thresholds, and document UBO identification processes.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=30,
                    expected_evidence_after=["UPDATED_POLICY", "AUDIT_FINDINGS", "REMEDIATION_PLAN"],
                ),
            ],
            missing_criteria=[
                "No written AML/CFT program documented",
                "No board-level oversight or governance structure",
                "CDD procedures not formalized",
                "Transaction monitoring system not in place",
            ],
            partial_criteria=[
                "Policy exists but predates current regulations (>2 years old)",
                "CDD procedures incomplete for complex customers",
                "Transaction monitoring rules not aligned with CBUAE guidance",
                "UBO identification process incomplete",
            ],
            supported_criteria=[
                "Current, board-approved AML/CFT program with clear governance",
                "Comprehensive CDD/EDD procedures aligned with CBUAE Module 5.1",
                "Automated transaction monitoring with documented thresholds",
                "SAR filing procedures with documented escalation path",
            ],
            risk_raise_criteria=[
                "No policy review in past 12 months",
                "CDD not updated for high-risk customers annually",
                "SAR filing delays exceeding regulatory timelines",
                "Transaction monitoring system failures or blind spots",
            ],
            retrieval_tags=["aml", "cft", "program", "policy", "cbuae", "dfsa"],
            corpus_hints=["AML program document", "CFT policy", "CBUAE compliance", "DFSA rulebook"],
            source_types=["POLICY_DOCUMENT", "BOARD_MINUTES", "SYSTEM_CONFIG", "AUDIT_REPORT"],
        ),
        JurisdictionControl(
            control_id="UAE-AML-02",
            control_name="Customer Due Diligence (CDD) - Identification and Verification",
            control_description="Financial institution must conduct CDD for all customers before establishing business relationships. CDD must include customer identification, nationality/residency verification, beneficial owner identification, and source of funds assessment. Must be completed before account activation and updated periodically per risk profile.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Module 5.1.2; DFSA Rulebook AML Module 5.2.1",
            severity=Severity.CRITICAL,
            regulatory_reference="CBUAE Circular 144/2024, Section 2.1; DFSA AML Module 5.2.1; UAE Federal Law No. 20/2018",
            risk_if_missing="Regulatory enforcement, monetary penalties, inability to onboard customers, failure to identify beneficial owners and source of funds, reputational damage.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="CDD_SAMPLE",
                    description="Sample CDD files for minimum 3 customers showing completed identification, verification, and approval workflow",
                    scoring_keywords=[
                        "customer identification",
                        "CDD file",
                        "identity verification",
                        "customer approval",
                        "beneficial owner",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                    examples=["CDD_Customer_001.pdf", "CDD_Customer_002.pdf"],
                ),
                EvidenceRequirement(
                    document_type="VERIFICATION_PROCESS",
                    description="Documented verification process with identity document samples, source of funds assessment, and beneficial owner identification",
                    scoring_keywords=[
                        "verification",
                        "identity document",
                        "source of funds",
                        "beneficial owner identification",
                        "UBO",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement CDD procedures for all customers. Establish document collection process (ID, utility bills), beneficial owner identification process, source of funds assessment. Create CDD file template. Train staff on CDD requirements. Implement system controls to enforce completion before account activation.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=45,
                    expected_evidence_after=["CDD_FILES", "TRAINING_RECORDS", "SYSTEM_SCREENSHOTS"],
                ),
            ],
            missing_criteria=[
                "No CDD process documented",
                "Customers onboarded without ID verification",
                "No beneficial owner identification",
                "No source of funds assessment",
            ],
            partial_criteria=[
                "CDD exists for new customers but not legacy customers",
                "Identity verified but beneficial owner not identified",
                "CDD updated inconsistently based on risk profile",
            ],
            supported_criteria=[
                "Comprehensive CDD completed before account activation",
                "Identity verified against government databases or physical documents",
                "Beneficial owner identified and verified per CBUAE guidance",
                "Source of funds assessed and documented for high-risk customers",
            ],
            risk_raise_criteria=[
                "CDD files missing for any active customer",
                "Identity documents not independently verified",
                "CDD not updated for customers for >2 years",
            ],
            retrieval_tags=["cdd", "kyc", "identification", "verification", "customer"],
            corpus_hints=["CDD procedure", "Customer identification", "Beneficial owner", "KYC documentation"],
            source_types=["CDD_FILE", "PROCEDURE_DOCUMENT", "TRAINING_MATERIAL"],
        ),
        JurisdictionControl(
            control_id="UAE-AML-03",
            control_name="Enhanced Due Diligence (EDD) - High-Risk Customer Assessment",
            control_description="Financial institution must conduct Enhanced Due Diligence (EDD) for high-risk customers including PEPs (Politically Exposed Persons), sanctions-listed parties, shell corporations, and customers in high-risk jurisdictions. EDD includes additional verification steps, senior management approval, and ongoing enhanced monitoring.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Module 5.1.3; DFSA Rulebook AML Module 5.2.2",
            severity=Severity.CRITICAL,
            regulatory_reference="CBUAE Circular 144/2024, Section 2.2; DFSA AML Module 5.2.2; UN Security Council sanctions resolutions",
            risk_if_missing="Facilitation of sanctions violations, money laundering through high-risk customers, PEP transactions, regulatory enforcement, criminal liability.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="EDD_PROCEDURE",
                    description="Written procedure defining high-risk customer categories and EDD requirements including PEP screening, source of wealth verification, and beneficial ownership verification",
                    scoring_keywords=[
                        "enhanced due diligence",
                        "EDD",
                        "high-risk customer",
                        "PEP screening",
                        "source of wealth",
                        "beneficial ownership",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="PEP_SCREENING_SYSTEM",
                    description="Evidence of automated PEP screening system with sanctions list integration and periodic updates",
                    scoring_keywords=[
                        "PEP screening",
                        "sanctions list",
                        "automated screening",
                        "compliance system",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="EDD_SAMPLE",
                    description="Sample EDD files for 2-3 high-risk customers showing source of wealth verification and senior management approval",
                    scoring_keywords=[
                        "EDD file",
                        "source of wealth",
                        "management approval",
                        "high-risk customer",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop EDD procedure defining high-risk customer categories. Implement PEP screening system with sanctions list integration. Create senior management approval workflow. Establish source of wealth verification documentation process. Train staff on EDD requirements.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=40,
                    expected_evidence_after=["EDD_PROCEDURE", "SCREENING_SYSTEM", "TRAINING_RECORDS"],
                ),
            ],
            missing_criteria=[
                "No EDD procedure documented",
                "No PEP screening system in place",
                "High-risk customers not identified or approved",
            ],
            partial_criteria=[
                "EDD process exists but not applied systematically",
                "Manual PEP screening without automation",
                "Senior management approval not consistently documented",
            ],
            supported_criteria=[
                "Documented EDD procedure aligned with CBUAE guidance",
                "Automated PEP/sanctions screening with regular updates",
                "Source of wealth verification for all high-risk customers",
                "Senior management approval documented for PEPs",
            ],
            risk_raise_criteria=[
                "Identified PEP without corresponding EDD documentation",
                "PEP screening system not updated in past 6 months",
            ],
            retrieval_tags=["edd", "pep", "sanctions", "high-risk", "kyc"],
            corpus_hints=["EDD procedure", "PEP screening", "Enhanced due diligence", "Source of wealth"],
            source_types=["PROCEDURE_DOCUMENT", "SYSTEM_CONFIG", "EDD_FILE"],
        ),
        JurisdictionControl(
            control_id="UAE-AML-04",
            control_name="Transaction Monitoring and Suspicious Activity Detection",
            control_description="Financial institution must maintain automated transaction monitoring system to detect suspicious activities and patterns. System must flag transactions meeting defined risk criteria, generate alerts for manual review, escalate high-severity cases, and maintain alert documentation for regulatory review. Thresholds must be calibrated to customer risk profiles and transaction patterns.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Module 5.1.4; DFSA Rulebook AML Module 5.3",
            severity=Severity.CRITICAL,
            regulatory_reference="CBUAE Circular 144/2024, Section 2.3; DFSA AML Module 5.3",
            risk_if_missing="Failure to detect money laundering and terrorist financing, regulatory enforcement, reputational damage, system-level control breakdown.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="MONITORING_SYSTEM_CONFIG",
                    description="Technical documentation of transaction monitoring system including alert rules, threshold parameters, and escalation procedures",
                    scoring_keywords=[
                        "transaction monitoring",
                        "alert rules",
                        "threshold",
                        "monitoring system",
                        "configuration",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="ALERT_SAMPLE",
                    description="Sample alerts with investigation outcomes, showing alert generation, review process, and closure documentation",
                    scoring_keywords=[
                        "alert",
                        "investigation",
                        "suspicious activity",
                        "alert review",
                        "case closure",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="MONITORING_PROCEDURE",
                    description="Written procedure for alert investigation, escalation, and SAR determination",
                    scoring_keywords=[
                        "monitoring procedure",
                        "alert investigation",
                        "escalation",
                        "SAR",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement automated transaction monitoring system with alert rules calibrated to risk. Define alert investigation procedure with timelines. Establish SAR escalation path. Configure system for high-value transactions (AED 50K+), round-tripping, rapid transfers, and unusual patterns. Train investigators.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=50,
                    expected_evidence_after=["SYSTEM_CONFIG", "ALERT_SAMPLES", "INVESTIGATION_DOCS"],
                ),
            ],
            missing_criteria=[
                "No transaction monitoring system",
                "Monitoring rules not documented",
                "No alert investigation procedure",
            ],
            partial_criteria=[
                "Manual monitoring without systematic rules",
                "Alert investigation inconsistent or incomplete",
                "Thresholds not calibrated to risk profiles",
            ],
            supported_criteria=[
                "Automated monitoring system with documented rules",
                "Alerts generated for suspicious patterns",
                "Timely investigation (24-48 hours)",
                "Clear SAR escalation path documented",
            ],
            risk_raise_criteria=[
                "High-value transactions not monitored",
                "Alert backlog exceeding 30 days",
                "False positive rate >80%",
            ],
            retrieval_tags=["transaction_monitoring", "aml", "alert", "suspicious_activity"],
            corpus_hints=["Monitoring system", "Alert procedure", "Suspicious activity", "Transaction monitoring"],
            source_types=["SYSTEM_CONFIG", "PROCEDURE_DOCUMENT", "ALERT_SAMPLE"],
        ),
        JurisdictionControl(
            control_id="UAE-AML-05",
            control_name="Suspicious Activity Reporting (SAR) to CBUAE/DFSA",
            control_description="Financial institution must file Suspicious Activity Reports (SAR) with CBUAE or DFSA within 10 business days of detection of suspicious activity. SAR must include customer information, transaction details, reason for suspicion, and investigation findings. Institution must maintain SAR documentation and respond to regulator inquiries.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Module 5.1.5; DFSA Rulebook AML Module 5.4",
            severity=Severity.CRITICAL,
            regulatory_reference="CBUAE Circular 144/2024, Section 2.4; DFSA AML Module 5.4; UAE Federal Law No. 20/2018",
            risk_if_missing="Failure to report suspicious activities, regulatory enforcement, monetary penalties, loss of regulatory confidence.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="SAR_POLICY",
                    description="Written policy defining suspicious activity, SAR filing requirements, timelines, and escalation procedures",
                    scoring_keywords=[
                        "SAR policy",
                        "suspicious activity report",
                        "reporting procedure",
                        "filing deadline",
                        "10 business days",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SAR_SAMPLE",
                    description="Sample SARs filed with CBUAE/DFSA showing transaction details, investigation findings, and filing confirmation",
                    scoring_keywords=[
                        "SAR",
                        "filed",
                        "CBUAE",
                        "DFSA",
                        "confirmation",
                        "suspicious activity report",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SAR_TRACKING",
                    description="SAR tracking log with filing dates, subjects, and regulator acknowledgments",
                    scoring_keywords=[
                        "SAR tracking",
                        "filing log",
                        "SAR record",
                        "acknowledgment",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Establish SAR policy with clear filing criteria and timelines. Create SAR form and filing procedures. Identify SAR officer responsible for filing. Establish CBUAE/DFSA submission mechanism. Create tracking log for all SARs. Train staff on SAR requirements and investigation process.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=25,
                    expected_evidence_after=["SAR_POLICY", "SAR_FORM", "TRACKING_LOG", "TRAINING"],
                ),
            ],
            missing_criteria=[
                "No SAR filing policy documented",
                "No SARs filed despite suspicious activities detected",
                "No SAR tracking mechanism",
            ],
            partial_criteria=[
                "SARs filed but with delays exceeding timelines",
                "SAR investigation incomplete or lacking detail",
                "No tracking of filed SARs",
            ],
            supported_criteria=[
                "SAR policy documented and communicated",
                "All suspicious activities escalated to SAR officer",
                "SARs filed within 10 business day deadline",
                "Complete tracking and documentation maintained",
            ],
            risk_raise_criteria=[
                "SAR filing delays exceeding deadline",
                "No SARs filed despite alerts",
                "Regulator follow-up on missing SARs",
            ],
            retrieval_tags=["sar", "suspicious_activity", "reporting", "cbuae", "dfsa"],
            corpus_hints=["SAR filing", "Suspicious activity report", "CBUAE reporting", "Regulatory filing"],
            source_types=["POLICY_DOCUMENT", "SAR_FORM", "TRACKING_LOG", "CONFIRMATION"],
        ),
        JurisdictionControl(
            control_id="UAE-AML-06",
            control_name="Compliance Training and Awareness Program",
            control_description="Financial institution must provide mandatory AML/CFT training to all staff involved in customer relationship, transaction processing, and compliance functions. Training must cover customer identification, suspicious activity detection, SAR procedures, and sanctions compliance. Training must be provided at onboarding and annually, with documentation and attendance records.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Module 5.1.6; DFSA Rulebook AML Module 5.5",
            severity=Severity.HIGH,
            regulatory_reference="CBUAE Circular 144/2024, Section 2.5; DFSA AML Module 5.5",
            risk_if_missing="Staff unable to identify suspicious activities, poor compliance culture, regulatory enforcement, reputational damage.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="TRAINING_PROGRAM",
                    description="Written training program covering AML/CFT requirements, CDD, EDD, transaction monitoring, and SAR procedures",
                    scoring_keywords=[
                        "training program",
                        "AML training",
                        "CFT training",
                        "curriculum",
                        "training material",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="TRAINING_RECORDS",
                    description="Training attendance records showing all staff completed initial and annual training with signatures and dates",
                    scoring_keywords=[
                        "training attendance",
                        "training record",
                        "staff training",
                        "completion",
                        "training log",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="TRAINING_MATERIAL",
                    description="Sample training slides, handouts, or e-learning modules covering AML/CFT topics",
                    scoring_keywords=[
                        "training material",
                        "slide deck",
                        "handout",
                        "e-learning",
                        "training content",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop AML/CFT training program covering CDD, EDD, transaction monitoring, SAR, and sanctions. Schedule onboarding training for all staff. Create annual refresher training. Implement attendance tracking and completion documentation. Consider e-learning platform for scalability.",
                    owner_type="HR_COMPLIANCE",
                    priority="HIGH",
                    estimated_effort_days=20,
                    expected_evidence_after=["TRAINING_PROGRAM", "ATTENDANCE_RECORDS", "TRAINING_MATERIAL"],
                ),
            ],
            missing_criteria=[
                "No training program documented",
                "No training conducted",
                "No attendance records",
            ],
            partial_criteria=[
                "Training conducted but not annual refresher",
                "Some staff not trained",
                "Attendance records incomplete",
            ],
            supported_criteria=[
                "Comprehensive training program covering all AML/CFT requirements",
                "All staff trained at onboarding",
                "Annual refresher training documented",
                "Complete attendance records maintained",
            ],
            risk_raise_criteria=[
                "Staff with no training records",
                "Annual training not conducted",
                "New hires not trained before customer interactions",
            ],
            retrieval_tags=["training", "aml", "cft", "compliance", "staff_development"],
            corpus_hints=["Training program", "Compliance training", "AML awareness", "Staff training"],
            source_types=["TRAINING_DOCUMENT", "ATTENDANCE_LOG", "TRAINING_MATERIAL"],
        ),
        JurisdictionControl(
            control_id="UAE-AML-07",
            control_name="AML/CFT Internal Audit and Compliance Review",
            control_description="Financial institution must conduct independent internal audit of AML/CFT program at least annually. Audit must assess policy compliance, control effectiveness, transaction monitoring performance, and SAR procedures. Institution must document audit findings and remediate identified gaps within defined timelines.",
            domain=Domain.AML_KYC,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Module 5.1.7; DFSA Rulebook AML Module 5.6",
            severity=Severity.HIGH,
            regulatory_reference="CBUAE Circular 144/2024, Section 2.6; DFSA AML Module 5.6",
            risk_if_missing="Undetected AML/CFT control weaknesses, regulatory enforcement, reputational damage.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="AUDIT_PLAN",
                    description="Annual internal audit plan documenting AML/CFT audit scope, procedures, and schedule",
                    scoring_keywords=[
                        "audit plan",
                        "internal audit",
                        "AML audit",
                        "audit scope",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="AUDIT_REPORT",
                    description="Internal audit report with findings, recommendations, and remediation tracking",
                    scoring_keywords=[
                        "audit report",
                        "internal audit",
                        "findings",
                        "remediation",
                        "audit conclusion",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="MANAGEMENT_RESPONSE",
                    description="Management response to audit findings with remediation plans and responsible parties",
                    scoring_keywords=[
                        "management response",
                        "remediation plan",
                        "management letter",
                        "corrective action",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Establish annual internal audit program for AML/CFT. Engage internal audit or external auditor. Define audit scope covering policy compliance, control effectiveness, and transaction monitoring. Document findings and management responses. Track remediation of identified gaps.",
                    owner_type="AUDIT_FUNCTION",
                    priority="HIGH",
                    estimated_effort_days=30,
                    expected_evidence_after=["AUDIT_PLAN", "AUDIT_REPORT", "MANAGEMENT_RESPONSE"],
                ),
            ],
            missing_criteria=[
                "No internal audit conducted",
                "No audit plan documented",
                "No documented findings or remediation",
            ],
            partial_criteria=[
                "Audit conducted but findings not documented",
                "Remediation not tracked",
                "Audit not conducted annually",
            ],
            supported_criteria=[
                "Annual internal audit plan established",
                "Audit performed by independent function",
                "Findings documented with recommendations",
                "Management response tracked with remediation timelines",
            ],
            risk_raise_criteria=[
                "No audit conducted in past 12 months",
                "Audit findings remediation delayed >90 days",
            ],
            retrieval_tags=["audit", "aml", "internal_audit", "compliance_review"],
            corpus_hints=["Internal audit", "Audit report", "AML audit", "Compliance review"],
            source_types=["AUDIT_PLAN", "AUDIT_REPORT", "MANAGEMENT_RESPONSE"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # SANCTIONS DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="UAE-SANCTIONS-01",
            control_name="Sanctions Screening - UN, US OFAC, and UAE Lists",
            control_description="Financial institution must screen all customers, beneficial owners, and transactions against UN Security Council sanctions lists, US OFAC lists (SDN, HQA), and UAE Ministry of Foreign Affairs lists. Screening must occur at customer onboarding and periodically (monthly minimum). Positive matches must be escalated immediately.",
            domain=Domain.SANCTIONS,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.DFSA,
            regime_mapping="DFSA Rulebook AML Module 5.7; UAE Federal Law No. 20/2018",
            severity=Severity.CRITICAL,
            regulatory_reference="DFSA AML Module 5.7; UN Security Council Resolutions; US Executive Orders; UAE Ministry of Foreign Affairs Sanctions List",
            risk_if_missing="Sanctions violations, criminal liability, monetary penalties, license revocation, reputational damage.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="SANCTIONS_SCREENING_SYSTEM",
                    description="Automated sanctions screening system with integration to UN, OFAC, and UAE lists with regular updates",
                    scoring_keywords=[
                        "sanctions screening",
                        "OFAC",
                        "UN sanctions",
                        "screening system",
                        "SDN list",
                    ],
                    confidence_threshold=0.90,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SCREENING_PROCEDURE",
                    description="Procedure documenting sanctions screening at onboarding, ongoing monitoring, and positive match escalation",
                    scoring_keywords=[
                        "screening procedure",
                        "sanctions procedure",
                        "OFAC procedure",
                        "positive match",
                        "escalation",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SCREENING_RECORDS",
                    description="Sample screening records showing dates, lists screened, and clearance documentation",
                    scoring_keywords=[
                        "screening record",
                        "screening log",
                        "clearance",
                        "match result",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement automated sanctions screening system. Integrate UN, OFAC SDN, and UAE sanctions lists with weekly updates. Establish positive match protocol with immediate escalation to compliance officer. Screen all customers at onboarding and monthly ongoing. Document clearance for audit trail.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=45,
                    expected_evidence_after=["SCREENING_SYSTEM", "PROCEDURE", "SCREENING_RECORDS"],
                ),
            ],
            missing_criteria=[
                "No sanctions screening system",
                "Customers not screened against sanctions lists",
                "No ongoing monitoring",
            ],
            partial_criteria=[
                "Screening system exists but not comprehensive",
                "Lists not updated regularly",
                "Positive matches not escalated promptly",
            ],
            supported_criteria=[
                "Automated screening system integrated with major lists",
                "All customers screened at onboarding and monthly",
                "Lists updated weekly",
                "Positive matches escalated within 4 hours",
            ],
            risk_raise_criteria=[
                "Lists not updated in past 30 days",
                "Customer screened >6 months ago without update",
                "Positive match without documentation",
            ],
            retrieval_tags=["sanctions", "ofac", "screening", "un_sanctions"],
            corpus_hints=["Sanctions screening", "OFAC compliance", "UN sanctions", "Screening system"],
            source_types=["SYSTEM_CONFIG", "PROCEDURE_DOCUMENT", "SCREENING_RECORD"],
        ),
        JurisdictionControl(
            control_id="UAE-SANCTIONS-02",
            control_name="Sanctions Transaction Filtering and Blocking",
            control_description="Financial institution must implement transaction controls to prevent transfers to/from sanctioned parties. System must block transactions flagged by sanctions screening. For transactions with possible sanctions nexus, institution must escalate to compliance and obtain legal review before proceeding. Blocked transactions must be documented.",
            domain=Domain.SANCTIONS,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.DFSA,
            regime_mapping="DFSA Rulebook AML Module 5.8; UAE Federal Law No. 20/2018",
            severity=Severity.CRITICAL,
            regulatory_reference="DFSA AML Module 5.8; US Executive Order 13224; UN SC Resolution 1373",
            risk_if_missing="Sanctions violations, criminal liability, monetary penalties, license revocation.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="TRANSACTION_FILTERING_CONFIG",
                    description="System configuration showing transaction filtering rules, blocking thresholds, and escalation procedures",
                    scoring_keywords=[
                        "transaction filtering",
                        "filtering rules",
                        "transaction block",
                        "configuration",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="BLOCKED_TRANSACTION_LOG",
                    description="Log of blocked transactions with reasons, escalation, and resolution documentation",
                    scoring_keywords=[
                        "blocked transaction",
                        "transaction block log",
                        "blocked transfer",
                        "blocking decision",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement transaction filtering system integrated with sanctions screening. Configure system to block transactions to/from flagged parties. Establish escalation procedure for borderline cases requiring legal review. Maintain blocked transaction log with business justification for any allowed transactions.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="CRITICAL",
                    estimated_effort_days=30,
                    expected_evidence_after=["FILTERING_CONFIG", "BLOCKED_LOG"],
                ),
            ],
            missing_criteria=[
                "No transaction filtering system",
                "Transactions to sanctioned parties not blocked",
                "No escalation procedure",
            ],
            partial_criteria=[
                "Filtering exists but incomplete",
                "Manual review process without automation",
                "Blocked transactions not documented",
            ],
            supported_criteria=[
                "Automated transaction filtering integrated with screening",
                "All transactions blocked appropriately",
                "Escalation procedure for borderline cases",
                "Complete documentation of all blocked transactions",
            ],
            risk_raise_criteria=[
                "Transaction processed to sanctioned party",
                "No blocked transaction log",
                "Transactions not filtered against latest sanctions lists",
            ],
            retrieval_tags=["sanctions", "transaction_filtering", "blocking", "controls"],
            corpus_hints=["Transaction filtering", "Sanctions blocking", "Transaction control", "Blocked transactions"],
            source_types=["SYSTEM_CONFIG", "TRANSACTION_LOG", "ESCALATION_RECORD"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # FRAUD DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="UAE-FRAUD-01",
            control_name="Fraud Detection and Prevention Systems",
            control_description="Financial institution must implement fraud detection and prevention systems to identify anomalous transaction patterns, unauthorized access attempts, and account compromise indicators. System must monitor for velocity abuse, unusual geographic patterns, and deviation from customer behavior baseline. Alerts must trigger manual review.",
            domain=Domain.FRAUD_TXN_MONITORING,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.DFSA,
            regime_mapping="DFSA Rulebook OPS Module 2.3.1; CBU AE Risk Management Guidance",
            severity=Severity.HIGH,
            regulatory_reference="DFSA Operational Risk Module 2.3.1; CBUAE Risk Management Guidance 2024",
            risk_if_missing="Undetected fraud, financial losses, customer trust erosion, reputational damage.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="FRAUD_DETECTION_SYSTEM",
                    description="Fraud detection system documentation including rules, thresholds, and machine learning models",
                    scoring_keywords=[
                        "fraud detection",
                        "fraud system",
                        "anomaly detection",
                        "fraud rules",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="FRAUD_ALERTS",
                    description="Sample fraud alerts with investigation outcomes and resolution",
                    scoring_keywords=[
                        "fraud alert",
                        "fraud investigation",
                        "suspicious transaction",
                        "fraud case",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Implement fraud detection system with rules for velocity abuse, unusual patterns, geographic anomalies. Establish alert investigation procedure with timeline. Create fraud investigation team. Train staff on fraud detection and reporting. Monitor system effectiveness monthly.",
                    owner_type="FRAUD_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=40,
                    expected_evidence_after=["FRAUD_SYSTEM", "ALERT_SAMPLES", "INVESTIGATION_RECORDS"],
                ),
            ],
            missing_criteria=[
                "No fraud detection system",
                "No fraud monitoring",
                "No documented fraud procedure",
            ],
            partial_criteria=[
                "Fraud system exists but not comprehensive",
                "Manual fraud detection without automation",
                "Alert investigation inconsistent",
            ],
            supported_criteria=[
                "Automated fraud detection system with documented rules",
                "Alerts generated for suspicious patterns",
                "Timely investigation and resolution",
                "Regular system tuning based on performance metrics",
            ],
            risk_raise_criteria=[
                "High false positive rate (>85%)",
                "Fraud not detected within organization",
                "Alert backlog exceeding 30 days",
            ],
            retrieval_tags=["fraud", "detection", "prevention", "transaction_monitoring"],
            corpus_hints=["Fraud detection", "Fraud prevention", "Anomaly detection", "Fraud system"],
            source_types=["SYSTEM_CONFIG", "ALERT_SAMPLE", "INVESTIGATION_RECORD"],
        ),
        JurisdictionControl(
            control_id="UAE-FRAUD-02",
            control_name="Fraud Investigation and Incident Response",
            control_description="Financial institution must establish procedures for investigating detected fraud cases, including victim notification, fund recovery, and law enforcement reporting. Procedures must include evidence preservation, forensic investigation, and documentation of investigation findings. Institution must maintain fraud loss records and identify trends.",
            domain=Domain.FRAUD_TXN_MONITORING,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.DFSA,
            regime_mapping="DFSA Operational Risk Module 2.3.2; CBU AE Incident Management Guidance",
            severity=Severity.HIGH,
            regulatory_reference="DFSA OPS Module 2.3.2; CBUAE Incident Management Guidance 2024; UAE Penal Code Article 396",
            risk_if_missing="Unrecovered fraud losses, delayed law enforcement reporting, customer dissatisfaction, regulatory enforcement.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="FRAUD_INVESTIGATION_PROCEDURE",
                    description="Written procedure for fraud investigation, victim notification, evidence preservation, and law enforcement reporting",
                    scoring_keywords=[
                        "fraud investigation",
                        "investigation procedure",
                        "victim notification",
                        "law enforcement",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="INVESTIGATION_SAMPLES",
                    description="Sample investigation files showing case documentation, findings, and resolution",
                    scoring_keywords=[
                        "investigation file",
                        "case file",
                        "investigation report",
                        "fraud case",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="FRAUD_LOSS_REGISTER",
                    description="Fraud loss register tracking incidents, amounts, recovery, and trends",
                    scoring_keywords=[
                        "fraud loss",
                        "loss register",
                        "fraud tracking",
                        "loss record",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop fraud investigation procedure with victim notification timeline, evidence preservation, and law enforcement reporting requirements. Create investigation file template. Establish fraud loss register. Train investigators on fraud investigation techniques and chain of custody. Define escalation thresholds for law enforcement reporting.",
                    owner_type="FRAUD_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=25,
                    expected_evidence_after=["PROCEDURE", "INVESTIGATION_TEMPLATE", "LOSS_REGISTER"],
                ),
            ],
            missing_criteria=[
                "No fraud investigation procedure",
                "Fraud cases not documented",
                "No victim notification process",
                "No law enforcement reporting",
            ],
            partial_criteria=[
                "Investigation procedure exists but incomplete",
                "Victim notification inconsistent",
                "Loss tracking incomplete",
            ],
            supported_criteria=[
                "Comprehensive investigation procedure documented",
                "Fraud cases investigated within 5 business days",
                "Victims notified within 24 hours",
                "Law enforcement reports filed appropriately",
                "Fraud loss register maintained and reviewed monthly",
            ],
            risk_raise_criteria=[
                "Fraud investigation delays exceeding 10 days",
                "Victim not notified of fraud",
                "Law enforcement not reported for reportable incidents",
            ],
            retrieval_tags=["fraud_investigation", "incident_response", "law_enforcement"],
            corpus_hints=["Fraud investigation", "Incident response", "Victim notification", "Case file"],
            source_types=["PROCEDURE_DOCUMENT", "INVESTIGATION_FILE", "LOSS_REGISTER"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # GOVERNANCE DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="UAE-GOV-01",
            control_name="Compliance Governance - Board Oversight and Compliance Officer",
            control_description="Financial institution must establish compliance governance structure with designated compliance officer reporting to board or senior management committee. Compliance officer must have direct access to board, adequate resources, and independence from business lines. Board must review compliance status quarterly.",
            domain=Domain.GOVERNANCE_VENDOR,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Corporate Governance Module 1.2; DFSA Governance Module 1.2",
            severity=Severity.HIGH,
            regulatory_reference="CBUAE Corporate Governance Module 1.2; DFSA Governance Module 1.2; UAE Corporate Governance Code",
            risk_if_missing="Weak compliance oversight, undetected control failures, regulatory enforcement, reputational damage.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="GOVERNANCE_CHARTER",
                    description="Board charter or governance document defining compliance officer role, responsibilities, and reporting line",
                    scoring_keywords=[
                        "board charter",
                        "governance document",
                        "compliance officer",
                        "reporting line",
                        "board oversight",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="BOARD_MINUTES",
                    description="Board minutes from past 12 months showing quarterly compliance reviews and decisions",
                    scoring_keywords=[
                        "board minutes",
                        "compliance review",
                        "board meeting",
                        "governance discussion",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="COMPLIANCE_OFFICER_CV",
                    description="Compliance officer CV showing qualifications and experience in compliance/regulatory matters",
                    scoring_keywords=[
                        "compliance officer",
                        "CV",
                        "experience",
                        "qualification",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Establish compliance governance structure with designated compliance officer reporting to board/audit committee. Define officer role and responsibilities in charter. Assign adequate budget and staff. Schedule quarterly board compliance reviews. Document officer interactions with board.",
                    owner_type="BOARD",
                    priority="HIGH",
                    estimated_effort_days=30,
                    expected_evidence_after=["CHARTER", "BOARD_MINUTES"],
                ),
            ],
            missing_criteria=[
                "No designated compliance officer",
                "Compliance officer reports to business line",
                "No board governance charter",
                "Board does not review compliance",
            ],
            partial_criteria=[
                "Compliance officer exists but insufficient resources",
                "Reporting line indirect (not to board/audit committee)",
                "Board review infrequent (<quarterly)",
            ],
            supported_criteria=[
                "Designated compliance officer with adequate independence",
                "Officer reports directly to board/audit committee",
                "Quarterly board compliance reviews documented",
                "Governance charter defines clear roles and responsibilities",
            ],
            risk_raise_criteria=[
                "Compliance officer reports to business head",
                "No board compliance review in past 6 months",
            ],
            retrieval_tags=["governance", "board", "compliance_officer", "oversight"],
            corpus_hints=["Board governance", "Compliance officer", "Board charter", "Governance structure"],
            source_types=["CHARTER", "BOARD_MINUTES", "JOB_DESCRIPTION"],
        ),
        JurisdictionControl(
            control_id="UAE-GOV-02",
            control_name="Regulatory Compliance Reporting and Regulatory Filings",
            control_description="Financial institution must file all required regulatory reports with CBUAE and DFSA on schedule. Reports include quarterly financial reports, regulatory returns, suspicious activity reports (SARs), and incident reports. Institution must maintain filing calendar and track submission confirmations.",
            domain=Domain.GOVERNANCE_VENDOR,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Regulatory Reporting Module 2.1; DFSA Reporting Module 2.1",
            severity=Severity.HIGH,
            regulatory_reference="CBUAE Regulatory Reporting Module 2.1; DFSA Reporting Module 2.1; UAE Securities and Commodities Authority Rules",
            risk_if_missing="Missing regulatory reports, regulatory enforcement, monetary penalties, license suspension.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="FILING_CALENDAR",
                    description="Calendar documenting all required regulatory filings with deadlines and responsible parties",
                    scoring_keywords=[
                        "filing calendar",
                        "regulatory filing",
                        "filing deadline",
                        "reporting schedule",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="FILING_CONFIRMATIONS",
                    description="Submission confirmations and receipts for regulatory filings from CBUAE/DFSA for past 12 months",
                    scoring_keywords=[
                        "filing confirmation",
                        "submission receipt",
                        "filing receipt",
                        "regulatory confirmation",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="FILING_SAMPLES",
                    description="Sample regulatory filings (redacted if sensitive) showing content and format",
                    scoring_keywords=[
                        "regulatory report",
                        "filing sample",
                        "submission",
                        "regulatory return",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Create regulatory filing calendar with all required reports and deadlines. Identify responsible parties. Establish submission process with quality review. Create filing log to track submissions and confirmations. Set automated reminders 2 weeks before deadline.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=15,
                    expected_evidence_after=["FILING_CALENDAR", "FILING_LOG", "CONFIRMATIONS"],
                ),
            ],
            missing_criteria=[
                "No filing calendar",
                "Regulatory filings missed or late",
                "No filing confirmations",
            ],
            partial_criteria=[
                "Filing calendar exists but incomplete",
                "Filings submitted but occasionally late",
                "No tracking of confirmations",
            ],
            supported_criteria=[
                "Comprehensive filing calendar maintained",
                "All filings submitted on time",
                "Submission confirmations tracked and filed",
                "Escalation procedure for late/missing filings",
            ],
            risk_raise_criteria=[
                "Regulatory filing submitted late",
                "Missing filing confirmation",
                "Regulatory notice for missing filing",
            ],
            retrieval_tags=["regulatory_filing", "reporting", "compliance", "governance"],
            corpus_hints=["Regulatory filing", "Compliance reporting", "Filing calendar", "Regulatory report"],
            source_types=["FILING_CALENDAR", "CONFIRMATION", "FILING_LOG"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # LICENSING AND FILINGS DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="UAE-LIC-01",
            control_name="License Registration and Regulatory Authorization",
            control_description="Financial institution must maintain valid license from CBUAE or DFSA for all regulated activities. License must be current and conspicuously displayed. Institution must notify regulator of any material changes to operations, ownership, or senior management within 30 days. Institution must pay license fees on schedule.",
            domain=Domain.LICENSING_FILINGS,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Licensing Module 1.1; DFSA Licensing Module 1.1",
            severity=Severity.CRITICAL,
            regulatory_reference="CBUAE Licensing Module 1.1; DFSA Licensing Module 1.1; UAE Federal Law No. 10/1992",
            risk_if_missing="Unauthorized operation, regulatory enforcement, license revocation, criminal liability.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="LICENSE_CERTIFICATE",
                    description="Valid license certificate from CBUAE or DFSA showing license number, scope, and expiration date",
                    scoring_keywords=[
                        "license",
                        "license certificate",
                        "regulatory license",
                        "authorization",
                        "license number",
                    ],
                    confidence_threshold=0.95,
                    is_mandatory=True,
                    examples=["Financial_License_Certificate.pdf"],
                ),
                EvidenceRequirement(
                    document_type="LICENSE_APPROVAL_LETTER",
                    description="Original license approval letter from CBUAE or DFSA detailing activities and conditions",
                    scoring_keywords=[
                        "license approval",
                        "license letter",
                        "regulatory approval",
                        "license conditions",
                    ],
                    confidence_threshold=0.90,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="LICENSE_RENEWAL_EVIDENCE",
                    description="Evidence of license renewal or confirmation of current status within past 12 months",
                    scoring_keywords=[
                        "license renewal",
                        "renewal confirmation",
                        "license status",
                        "current license",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Apply for financial services license from CBUAE or DFSA based on entity type and activities. Prepare application with financial statements, governance documentation, and business plan. Submit with required fees. Obtain license approval letter and display license certificate. Establish license renewal calendar.",
                    owner_type="BOARD",
                    priority="CRITICAL",
                    estimated_effort_days=90,
                    expected_evidence_after=["LICENSE_CERTIFICATE", "APPROVAL_LETTER", "RENEWAL_NOTICE"],
                ),
            ],
            missing_criteria=[
                "No valid license",
                "Operating without regulatory authorization",
                "License expired",
            ],
            partial_criteria=[
                "License obtained but scope limited",
                "License renewal process started but not finalized",
            ],
            supported_criteria=[
                "Valid license from CBUAE or DFSA",
                "License scope covers all activities",
                "License displayed conspicuously",
                "Renewal confirmed within past 12 months",
            ],
            risk_raise_criteria=[
                "License expired",
                "License renewal not processed",
                "Regulatory notice regarding license status",
            ],
            retrieval_tags=["license", "regulatory_authorization", "licensing"],
            corpus_hints=["License certificate", "Regulatory license", "Authorization", "License approval"],
            source_types=["LICENSE_CERTIFICATE", "APPROVAL_LETTER", "RENEWAL_NOTICE"],
        ),
        JurisdictionControl(
            control_id="UAE-LIC-02",
            control_name="License Condition Compliance and Material Change Notification",
            control_description="Financial institution must comply with all conditions specified in license approval. Institution must notify regulator within 30 days of any material changes including change of ownership, senior management, business lines, or location. Change notifications must include updated governance documentation and business plan as required.",
            domain=Domain.LICENSING_FILINGS,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.CBUAE,
            regime_mapping="CBUAE Licensing Module 1.2; DFSA Licensing Module 1.2",
            severity=Severity.HIGH,
            regulatory_reference="CBUAE Licensing Module 1.2; DFSA Licensing Module 1.2; UAE Federal Law No. 10/1992",
            risk_if_missing="License violation, regulatory enforcement, license suspension/revocation.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="LICENSE_CONDITIONS",
                    description="Written list of license conditions extracted from license approval letter with compliance status for each",
                    scoring_keywords=[
                        "license conditions",
                        "license requirements",
                        "compliance conditions",
                        "license terms",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="CHANGE_NOTIFICATION",
                    description="Material change notifications submitted to regulator within 30 days of change with supporting documentation",
                    scoring_keywords=[
                        "change notification",
                        "material change",
                        "regulatory notification",
                        "ownership change",
                        "management change",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="COMPLIANCE_MONITORING",
                    description="Compliance monitoring log showing regular review of license conditions and confirmation of compliance",
                    scoring_keywords=[
                        "compliance monitoring",
                        "condition monitoring",
                        "compliance check",
                        "condition review",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Extract all license conditions from approval letter. Create compliance checklist. Establish process for identifying material changes (ownership, management, business lines, location). Implement notification procedure with 30-day requirement. Create change notification template. Establish annual compliance review.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=20,
                    expected_evidence_after=["CONDITIONS_LIST", "CHANGE_NOTIFICATION", "COMPLIANCE_LOG"],
                ),
            ],
            missing_criteria=[
                "License conditions not documented",
                "Material changes not reported to regulator",
                "No process for tracking material changes",
            ],
            partial_criteria=[
                "License conditions documented but not monitored",
                "Change notifications submitted late (>30 days)",
                "Some material changes not reported",
            ],
            supported_criteria=[
                "All license conditions documented and monitored",
                "Material changes reported within 30 days",
                "Change notifications include required documentation",
                "Regulator acknowledges all notifications",
            ],
            risk_raise_criteria=[
                "Unreported material change identified",
                "License condition violation",
                "Regulatory notice regarding compliance",
            ],
            retrieval_tags=["license_compliance", "regulatory_notification", "material_change"],
            corpus_hints=["License conditions", "Material change", "Regulatory notification", "Compliance monitoring"],
            source_types=["CONDITION_LIST", "CHANGE_NOTIFICATION", "COMPLIANCE_LOG"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # PRIVACY AND DATA PROTECTION DOMAIN (2 CONTROLS)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="UAE-PRIVACY-01",
            control_name="Data Protection Policy and Customer Privacy Rights",
            control_description="Financial institution must establish written privacy policy complying with DFSA Data Protection Module 3 and UAE data protection laws. Policy must describe collection, use, retention, and sharing of customer data. Institution must obtain customer consent for data processing and provide access rights. Policy must be published and communicated to customers.",
            domain=Domain.PRIVACY_DATA,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.DFSA,
            regime_mapping="DFSA Data Protection Module 3; UAE Federal Law No. 45/1992 (Personal Data Protection)",
            severity=Severity.HIGH,
            regulatory_reference="DFSA Data Protection Module 3; UAE Federal Law No. 45/1992; UAE Cabinet Resolution No. 12/2021",
            risk_if_missing="Unauthorized data use, customer complaints, regulatory enforcement, reputational damage, privacy breaches.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="PRIVACY_POLICY",
                    description="Written privacy policy published on website and provided to customers describing data collection, use, retention, and sharing",
                    scoring_keywords=[
                        "privacy policy",
                        "data protection",
                        "privacy notice",
                        "customer privacy",
                        "data handling",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="CONSENT_MECHANISM",
                    description="Documented consent mechanism for data processing with evidence of customer consent obtained",
                    scoring_keywords=[
                        "consent",
                        "data consent",
                        "customer consent",
                        "consent form",
                        "data processing consent",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="DATA_ACCESS_PROCEDURE",
                    description="Procedure allowing customers to access, correct, or delete their personal data",
                    scoring_keywords=[
                        "data access",
                        "customer access",
                        "data correction",
                        "data deletion",
                        "right to access",
                    ],
                    confidence_threshold=0.75,
                    is_mandatory=False,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop privacy policy complying with DFSA Module 3 and UAE laws. Describe data collection, use, retention, and sharing. Publish on website. Implement consent mechanism in account opening process. Create data access request procedure. Train staff on privacy requirements. Document customer communications.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=25,
                    expected_evidence_after=["PRIVACY_POLICY", "CONSENT_FORM", "PROCEDURE"],
                ),
            ],
            missing_criteria=[
                "No privacy policy",
                "No customer consent process",
                "Data handling not documented",
            ],
            partial_criteria=[
                "Privacy policy exists but incomplete",
                "Consent process not systematic",
                "No data access procedure",
            ],
            supported_criteria=[
                "Comprehensive privacy policy complying with regulations",
                "Consent obtained before processing",
                "Data access/correction/deletion procedures in place",
                "Regular policy review and updates",
            ],
            risk_raise_criteria=[
                "Privacy policy not published",
                "Customer consent not documented",
                "Data access request not processed",
            ],
            retrieval_tags=["privacy", "data_protection", "customer_privacy"],
            corpus_hints=["Privacy policy", "Data protection", "Privacy notice", "Customer privacy"],
            source_types=["PRIVACY_POLICY", "CONSENT_FORM", "PROCEDURE_DOCUMENT"],
        ),
        JurisdictionControl(
            control_id="UAE-PRIVACY-02",
            control_name="Data Security and Breach Response Procedures",
            control_description="Financial institution must implement data security controls to protect customer personal data from unauthorized access, disclosure, or loss. Controls must include encryption, access controls, audit trails, and regular security assessments. Institution must maintain breach response procedures and notify DFSA and customers of security breaches within required timelines.",
            domain=Domain.PRIVACY_DATA,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.DFSA,
            regime_mapping="DFSA Operational Risk Module 2.2; DFSA Data Protection Module 3.2",
            severity=Severity.HIGH,
            regulatory_reference="DFSA Operational Risk Module 2.2; DFSA Data Protection Module 3.2; UAE Cyber Security Strategy",
            risk_if_missing="Data breaches, unauthorized access, customer data theft, regulatory enforcement, reputational damage.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="DATA_SECURITY_POLICY",
                    description="Written data security policy specifying controls, encryption standards, access management, and audit procedures",
                    scoring_keywords=[
                        "data security",
                        "security policy",
                        "encryption",
                        "access control",
                        "security standard",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="SECURITY_ASSESSMENT",
                    description="Annual security assessment or penetration testing report showing control effectiveness",
                    scoring_keywords=[
                        "security assessment",
                        "penetration test",
                        "vulnerability assessment",
                        "security audit",
                        "security evaluation",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="BREACH_RESPONSE_PROCEDURE",
                    description="Breach response procedure with notification timelines and escalation process",
                    scoring_keywords=[
                        "breach response",
                        "breach notification",
                        "incident response",
                        "breach procedure",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop comprehensive data security policy with encryption, access controls, and audit trail requirements. Implement controls including encryption at rest/in transit, role-based access, and system monitoring. Conduct annual security assessment. Establish breach response procedure with DFSA notification requirement within 24 hours. Create breach notification template.",
                    owner_type="CISO",
                    priority="HIGH",
                    estimated_effort_days=45,
                    expected_evidence_after=["SECURITY_POLICY", "ASSESSMENT_REPORT", "BREACH_PROCEDURE"],
                ),
            ],
            missing_criteria=[
                "No data security policy",
                "No encryption controls",
                "No breach response procedure",
                "No security assessments",
            ],
            partial_criteria=[
                "Security controls exist but not comprehensive",
                "No annual security assessment",
                "Breach notification procedure incomplete",
            ],
            supported_criteria=[
                "Comprehensive security policy with encryption and access controls",
                "Annual security assessments showing control effectiveness",
                "Breach response procedure with 24-hour DFSA notification",
                "Customer breach notification within required timeline",
                "Audit logs maintained for access and changes",
            ],
            risk_raise_criteria=[
                "Unencrypted sensitive data",
                "No audit trail for data access",
                "Security breach not reported to DFSA",
            ],
            retrieval_tags=["data_security", "breach_response", "incident_response"],
            corpus_hints=["Data security", "Breach notification", "Incident response", "Security controls"],
            source_types=["SECURITY_POLICY", "ASSESSMENT_REPORT", "BREACH_PROCEDURE"],
        ),

        # ═════════════════════════════════════════════════════════════════════════
        # REAL ESTATE DOMAIN (1 CONTROL)
        # ═════════════════════════════════════════════════════════════════════════
        JurisdictionControl(
            control_id="UAE-RE-01",
            control_name="Real Estate Transaction Compliance - Property Financing and Beneficial Ownership",
            control_description="Financial institution providing real estate financing must conduct enhanced due diligence on property transactions. Procedures must verify beneficial ownership of property, source of funds for down payment, and identify high-risk transaction patterns. For commercial real estate, must verify ultimate beneficial owners and business purpose. Must assess sanctions risk and conduct ongoing monitoring of real estate portfolios.",
            domain=Domain.REAL_ESTATE,
            jurisdiction=JurisdictionCode.UAE,
            regulator=Regulator.DFSA,
            regime_mapping="DFSA Rulebook AML Module 5.2.3 (Real Estate Overlay); CBUAE Real Estate Risk Guidance",
            severity=Severity.HIGH,
            regulatory_reference="DFSA AML Module 5.2.3; CBUAE Real Estate Risk Guidance 2024; FATF Real Estate Mutual Evaluation Guidance",
            risk_if_missing="Real estate used for money laundering, sanctions evasion, terrorist financing, regulatory enforcement.",
            evidence_requirements=[
                EvidenceRequirement(
                    document_type="RE_FINANCING_PROCEDURE",
                    description="Documented procedure for real estate financing including beneficial ownership verification, source of funds verification, and transaction risk assessment",
                    scoring_keywords=[
                        "real estate",
                        "property financing",
                        "beneficial ownership",
                        "source of funds",
                        "transaction risk",
                    ],
                    confidence_threshold=0.85,
                    is_mandatory=True,
                ),
                EvidenceRequirement(
                    document_type="RE_TRANSACTION_SAMPLE",
                    description="Sample real estate transaction files showing beneficial ownership documentation, source of funds verification, and risk assessment",
                    scoring_keywords=[
                        "real estate file",
                        "property file",
                        "transaction file",
                        "beneficial owner",
                        "source of funds",
                    ],
                    confidence_threshold=0.80,
                    is_mandatory=True,
                ),
            ],
            remediation_templates=[
                RemediationTemplate(
                    gap_type="MISSING",
                    corrective_action="Develop real estate financing procedure requiring beneficial ownership verification through title deeds and registry checks. Require source of funds verification for down payment (bank statements, gift documentation). Assess transaction risk (price reasonableness, party relationships, funding sources). For commercial property, verify UBO and business purpose. Implement ongoing monitoring of portfolio.",
                    owner_type="COMPLIANCE_OFFICER",
                    priority="HIGH",
                    estimated_effort_days=30,
                    expected_evidence_after=["RE_PROCEDURE", "TRANSACTION_FILES", "MONITORING_SAMPLES"],
                ),
            ],
            missing_criteria=[
                "No real estate financing procedure",
                "Beneficial owner not verified for property",
                "Source of down payment funds not verified",
            ],
            partial_criteria=[
                "Procedure exists but not comprehensive",
                "Beneficial ownership verification incomplete",
                "High-value transactions not assessed for risk",
            ],
            supported_criteria=[
                "Comprehensive real estate procedure with beneficial ownership verification",
                "Source of funds verified for all down payments >AED 100K",
                "Transaction risk assessed for suspicious patterns",
                "Ongoing monitoring of real estate portfolio",
                "Commercial property UBO verification completed",
            ],
            risk_raise_criteria=[
                "Property financed without beneficial owner identification",
                "Unusual property price or funding source not questioned",
                "Commercial property financed without UBO verification",
            ],
            real_estate_overlays=[
                RealEstateOverlay(
                    scenario="Residential Buyer - Expatriate",
                    kyc_expectations="Identity verification, visa/residence permit, source of funds verification, employment verification, no PEP/sanctions screening required unless high-value (>AED 2M)",
                    source_of_funds_check=True,
                    beneficial_ownership_depth=1,
                    transaction_red_flags=[
                        "Funding from third party without clear relationship",
                        "Large gift from unknown source",
                        "Structuring (multiple small transfers)",
                        "Cash down payment >AED 500K",
                    ],
                    sector_specific_risks=[
                        "Expatriate vulnerability to employment termination/deportation",
                        "Currency risk for foreign exchange transactions",
                    ],
                ),
                RealEstateOverlay(
                    scenario="Commercial Property - Corporate Buyer",
                    kyc_expectations="Ultimate beneficial owner identification, company registration verification, corporate structure analysis, beneficial owner identity verification, PEP/sanctions screening for all beneficial owners, board resolution for purchase authorization",
                    source_of_funds_check=True,
                    beneficial_ownership_depth=3,
                    transaction_red_flags=[
                        "Shell company structure without clear business purpose",
                        "Rapid transfer between multiple entities",
                        "Financing from offshore jurisdictions without clear nexus",
                        "UBO identity concealment or use of nominees",
                    ],
                    sector_specific_risks=[
                        "Commercial property used as collateral for illicit funds",
                        "Transfer pricing issues between related entities",
                        "Property renting at below-market rates",
                    ],
                ),
                RealEstateOverlay(
                    scenario="Real Estate Developer - Large Transaction",
                    kyc_expectations="Source of development funding, investor beneficial ownership verification, project financing source verification, end-user customer KYC (for pre-sales), anti-corruption measures for government approvals",
                    source_of_funds_check=True,
                    beneficial_ownership_depth=2,
                    transaction_red_flags=[
                        "Funding from sanctioned jurisdictions",
                        "Investor identity concealment or use of complex structures",
                        "Rapid price changes between contracts",
                        "Large cash deposits into project accounts",
                    ],
                    sector_specific_risks=[
                        "Development project used for money laundering through buyer KYC gaps",
                        "Corruption in real estate development approvals",
                        "Funding from proceeds of corruption in origin country",
                    ],
                ),
            ],
            retrieval_tags=["real_estate", "property_financing", "beneficial_ownership"],
            corpus_hints=["Real estate", "Property financing", "Beneficial owner", "Property transaction"],
            source_types=["RE_PROCEDURE", "TRANSACTION_FILE", "TITLE_DEED", "SOURCE_VERIFICATION"],
        ),
    ],
)
